### ISSUE TITLE
Spotify volume adjustment when Assistant is triggered

### ISSUE THREAD

**Issue by fede998-lll** [bugsounet/MMM-AssistantMk2#327]
Hi, I'm using raspotify to listen to music on my MM. I was wondering if there is a way to turn the volume down  the moment the assistant is activated just like real Alexa o Google Home.  Thanks

**Comment by bugsounet** [comment]
i will try to update MMM-Spotify recipe for control it

**Comment by bugsounet** [comment]
hi, i look at your issue

Spotify volume control is integred already

do you use [spotify recipe](https://github.com/eouia/MMM-AssistantMk2/wiki/Prepared-recipes#with-mmm-spotifyjs) ?

**Comment by bugsounet** [comment]
*already coded*
