### ISSUE TITLE
AssistantMK2 cannot triger RASPOTIFY to play a song

### ISSUE THREAD

**Issue by djdocta** [bugsounet/MMM-AssistantMk2#341]
**Describe the problem**
A clear and concise description of what the problem you have.
Hi,
This issue I have here is probably an already known issue but I've searched the forum and haven't found any solution for this.
I've installed the modules MMM-Spotify / MMM-AssistantMK2 (latest version) ... on my MM and it runs fine with RASPOTIFY (premium account) installed on my RI 4B. 
I'm using the default recipes in order to voice control spotify via AsssitantMK2 and this works fine but ...... ONLY if I manually launch a Spotify Client with the same account on another device (my PC or my phone). 
If I do not have another client running on a different device, I'm not able to ask AssistantMK2 to "play music on Spotify" even thought the RASPOTIFY is running correctly in the background.
The strange part is that the command is catched properly by AssistantMK2 but somehow he is unable to execute it an returns errors like this : 

[19:58:23.410] [ERROR]  TypeError: Cannot read property 'search' of null
2|mm     |     at Class.searchAndPlay (/home/pi/MagicMirror/modules/MMM-Spotify/node_helper.js:212:22)
2|mm     |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Spotify/node_helper.js:162:18)
2|mm     |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:113:11)
2|mm     |     at Socket.emit (events.js:182:13)
2|mm     |     at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
2|mm     |     at process._tickCallback (internal/process/next_tick.js:61:11)
2|mm     | [19:58:23.411] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
2|mm     | [19:58:23.412] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

If I ask for the same command when a SPOTIFY client is running on another device (with the same account), the it works fine, so one could say, launch simply the client at each time but this is annoying to me and I'm sure there is a way to do it without launching the client.  

**Environment:**
 - Device : RPI 4B
 - OS: Raspbian Buster
 - Versions : Latest MM with all the modules up to date (AssistantMK2/Spotify/Hotword/Youtube etc ...)

Thanks for the help.

**Comment by djdocta** [comment]
Thanks already for the feedback.

**Comment by djdocta** [comment]
Hey, any news on the below issue ? Maybe now that we changed owner REPO ? :-)

**Comment by bugsounet** [comment]
Hi, Actually, i have not premium access to test this issue
just waiting for @eouia inspect

**Comment by arlindonatal** [comment]
I have the same problem. @djdocta

**Comment by bugsounet** [comment]
corrected with the lasted version of MMM-Spotify
