### ISSUE TITLE
Not showing on MM

### ISSUE THREAD

**Issue by vekzla** [bugsounet/MMM-AssistantMk2#345]
**Describe the problem**
I have followed the install and many youtube links. install had no issues, however Google Assistant does not show up on LCD (top right) or respond to voice commands

**To Reproduce**

**Expected behavior**
should of worked if instructions followed or no broken installations

**Screenshots**
![image](https://user-images.githubusercontent.com/47047226/76865124-50f82e00-68b6-11ea-9580-40afce718787.png)

![image](https://user-images.githubusercontent.com/47047226/76865390-c401a480-68b6-11ea-8ba7-ee49b8f150e7.png)

**Environment:**
 - Device : RPI3+b
 - OS: Raspbian buster
 - Node Version :V10.19.0
 - Etc.

**Before you post issue, try this first**
- Confirm you have completed installation with instruction. (If you have a problem on installation step, find other similar issues or follow instruction carefully. But if you failed again, post issue here.)
- To make things simple, disable or omit or outcomment other modules from config.js except MMM-AssistantMk2 and MMM-Hotword.
- Add `verbose:true` to MMM-Assistant `config:{}` and `testMic:true` to MMM-Hotword `config:{}`. 
- Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
- If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.

Then report me.

**Comment by bugsounet** [comment]
hi, i think you have 2 intences of MagicMirror launched.
Surely one with pm2 and one with npm start.

just close the 2 intences (`CTRL C`) for npm session and `pm2 stop 0` for pm2 session

after you can relaunch MagicMirror application with `npm start` in root MagicMirror directory

**Comment by vekzla** [comment]
> hi, i think you have 2 intences of MagicMirror launched.
> Surely one with pm2 and one with npm start.
> 
> just close the 2 intences (`CTRL C`) for npm session and `pm2 stop 0` for pm2 session
> 
> after you can relaunch MagicMirror application with `npm start` in root MagicMirror directory

Thank you for your help, completed what you have asked however still having issues see pic below
![image](https://user-images.githubusercontent.com/47047226/76867153-3ffcec00-68b9-11ea-83b7-26e8d147d3bb.png)

**Comment by eouia** [comment]
Log says `no model to load` on hotword. You didn't describe models on your configuration. describe what model you will use. Or just use one of prepared recipes. read the docs and follow the instructions.

**Comment by bugsounet** [comment]
`[HOTWORD] No model to load`
I think you have a mismake in your config,
 can you read wiki doc for adding a recipe for activating AMk2

**Comment by vekzla** [comment]
thank you gents for your comment, see below my config file
![image](https://user-images.githubusercontent.com/47047226/76867818-28723300-68ba-11ea-9f3a-589deeb37d40.png)

**Comment by eouia** [comment]
I don't know how some guys can get these old configurations. You are using old version. Read the github repository to get recent updates and news.

**Comment by vekzla** [comment]
> I don't know how some guys can get these old configurations. You are using old version. Read the github repository to get recent updates and news.

understand your frustration with silly questions, are you able to point me to the right direction.
This is what i followed, and used auto install
https://github.com/eouia/MMM-AssistantMk2/wiki/Installation

thank you

**Comment by eouia** [comment]
I'm just curious HOW you have got the old configuration structure. Because we did effort to remove old documents from our repository, however, some users still show us this mysterious origins.  
Anyway, 

Configuration about MMM-Hotword exists here;
https://github.com/eouia/MMM-Hotword/wiki/Configuration

Configuration about MMM-AssistantMk2 exists here;
https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration-Sample

Two modules are independent, so if you want to know how to combinate, read this section carefully.
https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration-Sample#for-mmm-hotword

**Comment by vekzla** [comment]
> I'm just curious HOW you have got the old configuration structure. Because we did effort to remove old documents from our repository, however, some users still show us this mysterious origins.
> Anyway,
> 
> Configuration about MMM-Hotword exists here;
> https://github.com/eouia/MMM-Hotword/wiki/Configuration
> 
> Configuration about MMM-AssistantMk2 exists here;
> https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration-Structure
> https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration-Sample
> 
> Two modules are independent, so if you want to know how to combinate, read this section carefully.
> https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration-Sample#for-mmm-hotword

Thank you will crack on with your links, majority of us who are new to this follow videos makes it easier to follow (pic speaks a thousand words, let alone a video). I got stuck somewhere and fall in a rabbit hole at YouTube. Maybe create a video guide for noobs to follow. Once again thank you will report back asap.

**Comment by eouia** [comment]
If you get a success, You can make Video tutorial for others. :) Wish you a good luck.

**Comment by vekzla** [comment]
> If you get a success, You can make Video tutorial for others. :) Wish you a good luck.

Thanks, will keep you posted on my 6 sd card format. missing a step in the config.js file i am sure of it. just doing a clean install of hotboy and mk2 now. this will be the last one :( it may out do me

**Comment by cr4shydlo** [comment]
Did you got any luck ? 
I used configs from @eouia and now when i say Jarvis i see that Jarvis is recognized.. buty any other command is not. I try speak in Polish and English, and i get all the time Sorry i dont understand. Few time i got this moment after i say Jarvis. In my room is silent, and i think he dont get any other sound from background.

**Comment by bugsounet** [comment]
hi, we think that your issue is now solved
