### ISSUE TITLE
Device_Model_ID found

### ISSUE THREAD

**Issue by mattx38** [bugsounet/MMM-AssistantMk2#346]
Hello,

I cannot manage to register my mirror as Google Assistant related device.

When I enter this command (with my prject_id) :

curl -s -X POST -H "Content-Type: application/json" \
-H "Authorization: Bearer $ACCESSTOKEN" -d @deviceInstance.json \
https://embeddedassistant.googleapis.com/v1alpha2/projects/YOUR_PROJECT_ID/devices/

the result is : 
"error": {
    "code": 404,
    "message": "Could not create the device instance. No device model with device_model_id MMM2-63cd3-magicmirror-uh3dhy could be found.",
    "status": "NOT_FOUND"

I did it 20 times but it doesn't work at all and I don't understand why.
Can you help me ?

**Comment by eouia** [comment]
change **`YOUR_PROJECT_ID`** to your real project Id.

**Comment by mattx38** [comment]
Could you specify what is the real projetc Id instead of YOUR_PROJECT_ID ?

**Comment by eouia** [comment]
Ok. You probably miss `Register Model`
Go to https://console.actions.google.com then select your project.
On `Develop` Tab, you can find `Device registration` menu. It would look like this.
![image](https://user-images.githubusercontent.com/1720610/76941743-da325380-68fc-11ea-8fae-c2b0425623ec.png)
Then You can `Register model`

**Comment by mattx38** [comment]
I did this too

**Comment by eouia** [comment]
Hmmm. there is another way to register model 
https://developers.google.com/assistant/sdk/guides/service/python/embed/register-device#alternative-ways

**Comment by bugsounet** [comment]
solved by himself
