### ISSUE TITLE
New UI like LUCY

### ISSUE THREAD

**Issue by renzo79** [bugsounet/MMM-AssistantMk2#347]
Hello,

at first great work and the new improvements are awesome. Thanks for that.

I´ve an idea for a great eyecatcher but I´ve no experience with coding, therefore I´ve to write it here.

I love the functional range of this module, but I love the frontend of LUCY. It is a great eye-catcher when you call the Hotword and the LUCY-Face will be visible instead of the Google UI.

Is it possible to move or to use the Lucy or something similar frontend in this Project?

Thanks for you continuous work and Help

**Comment by eouia** [comment]
Ideally possible.
This module emits plenty of notifications about what this module is doing at that moment.
And with the plugins and addon, you can inject your hooking routines inside code directly.
And for UI, we made this module possible to implement user's own UI look.

So, I can bet, ideally possible.
But, implementation is your homework. :)
