### ISSUE TITLE
Compilation Issue during Install

### ISSUE THREAD

**Issue by etsandig** [bugsounet/MMM-AssistantMk2#348]
I have a compilation problem installing the module.  Followed instructions in wiki, but get the following (raspberry pi4, raspian).   Any idea what I am missing/doing wrong?

Thank you for your help.

pi@raspmm:~/MagicMirror/modules/MMM-AssistantMk2 $ npm install

> grpc@1.23.4 install /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.23.4/node-v79-linux-arm-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for grpc@1.23.4 and node@13.9.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp) 
.
.
.
  AR(target) Release/obj.target/libaddress_sorting.a
  COPY Release/libaddress_sorting.a
  CXX(target) Release/obj.target/grpc_node/ext/byte_buffer.o
  CXX(target) Release/obj.target/grpc_node/ext/call.o
../ext/call.cc: In function ‘bool grpc::node::CreateMetadataArray(v8::Local<v8::Object>, grpc_metadata_array*)’:
../ext/call.cc:104:58: error: no matching function for call to ‘v8::Array::Get(unsigned int&)’
     Local<String> current_key(Nan::To<String>(keys->Get(i)).ToLocalChecked());
                                                          ^
In file included from /home/pi/.cache/node-gyp/13.9.0/include/node/node.h:67,
                 from ../ext/call.cc:23:
...
...
...
This is followed by a bunch of other compilation errors.  I have installed gcc7 properly I think:
pi@raspmm:~ $ gcc --version
gcc (Raspbian 7.3.0-19) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by acimail01** [comment]
got the same error. try downgrade node version.

**Comment by eouia** [comment]
There could be a bunch of error messages, but however in the end of the installation, if electron-rebuild be completed, it could work.

**Comment by etsandig** [comment]
That was the issue, I was using node12 instead of node10.  after reinstalling the correct version the problem went away.   
Thank you for the help.
