### ISSUE TITLE
Assistant not picking up audio

### ISSUE THREAD

**Issue by MajestyBilly** [bugsounet/MMM-AssistantMk2#351]
Hey, my MMM-Hotword detects my hotword (computer) now, but when the assistant starts, it doesn't pick up my voice? Nothing happens, the three "dots" comes and bounces and after 20s the assistant closes again... I don't see any errors in my console related to the MMM-AssistantMk2.

Config:
`
{
	module: "MMM-AssistantMk2",
	position: "top_left",
	config: {
		assistantConfig: {
			latitude: 60.8261,
			longitude: 14.9921,
		},
		micConfig: {
			recorder: "arecord",
			device: "plughw:1",
			},
			recipes: [ "with-MMM-Hotword.js" ],
			profiles: {
				"default": {
					profileFile: "default.json",
					lang: "en-US"
			}
		},
	}
},
{
  module: "MMM-Hotword",
  position: "top_left",
  config: {
     chimeOnFinish: null,
     recipes: ["with-AMk2v3_smart-mirror.js"],
     mic: {
       recordProgram: "arecord",
       device: "plughw:1",
      },
      models: [
      {
        hotwords    : "computer",
        file        : "computer.umdl",
        sensitivity : "0.5",
      },
    ],
    commands: {
      "computer": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    }
  }
},
`

Any ideas?

**Comment by bugsounet** [comment]
hi, you have a mismake configuration on Hotword module,

you merge AMk2 v2 and v3 configuration, so il will not working

please correct your configuration with [this wiki help](https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration-Sample#for-mmm-hotword)

**Comment by MajestyBilly** [comment]
> hi, you have a mismake configuration on Hotword module,
> 
> you merge AMk2 v2 and v3 configuration, so il will not working
> 
> please correct your configuration with [this wiki help](https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration-Sample#for-mmm-hotword)

Thank you so much man! It copied those configurations and modified them a bit (position etc) and it worked! :) 
Question: How do I adjust the sensitivity now? I have noisy-smart-mirror but I want it even more sensitive.

**Comment by eouia** [comment]
In your recipe (I recommend copy and use your own from original source),
add sensitivity like this.
```js
{
        hotwords    : "computer",
        file        : "computer.umdl",
        sensitivity : "0.5",
      },
```

**Comment by bugsounet** [comment]
hello, we consider that your problem is solved.
do not hesitate to reopen an exit if necessary
