### ISSUE TITLE
Assistant error when hotword is detected

### ISSUE THREAD

**Issue by idmarco** [bugsounet/MMM-AssistantMk2#352]
Hi!

I have installed MMM-AssistantMk2 and MMM-Hotword, when my hotword is detected and the assistant listens, nothing responds. However, if I don't use a hotword, and I click on the logo, it´s OK.
In log file prints:
[23:44:42.196] [LOG]    [HOTWORD] Detector starts listening.
[23:45:05.943] [LOG]    [AMK2:BM] MP3 FILE CREATED
[23:45:05.946] [LOG]    [AMK2:AS] CONVERSATION_ERROR: Error: 14 UNAVAILABLE: Service unavailable.
[23:45:05.949] [LOG]    [AMK2:AS] >> This error might happen when improper configuration or invalid Mic setup.
[23:45:05.954] [LOG]    [AMK2] ASSISTANT_RESULT { session: 1585777474854,
  error: 'NO_RESPONSE',
  action: null,
  text: null,
  screen: null,
  audio: null,
  transcription: null,
  continue: false,
  volume: null,
  lastQuery:
   { type: 'TEXT',
     profile: { profileFile: 'default.json', lang: 'es-ES' },
     key: null,
     lang: null,
     useScreenOutput: true,
     useAudioOutput: true,
     useHTML5: false,
     session: 1585777474854,
     status: 'standby',
     chime: true,
     secretMode: false,
     sayMode: false } }
[23:45:06.018] [LOG]    [AMK2:SOUND] Audio starts with mpg321  /home/pi/MagicMirror/modules/MMM-AssistantMk2/resources/error.mp3
[23:45:06.797] [LOG]    [AMK2:SOUND] Audio ends

My config (I test it only with Assistant and Hotword modules):
{
      module: "MMM-AssistantMk2",
      position: "fullscreen_above",
      config: {
        debug: true,
        ui: "Classic", // Classic2 or Classic
        // if you want Google Home ui style
        // set Fullscreen ui AND fullscreen_above position
        assistantConfig: {
          projectId: "XXXXXXXX", // Required to use gaction.
          modelId: "XXXXXXXX", // (OPTIONAL for gaction)
          instanceId: "XXXXXXXX", // (OPTIONAL for gaction)
          latitude: 41.65606,
          longitude: -0.87734,
        },
        responseConfig: {
          useHTML5: true, // sound render by HTML5
          useScreenOutput: true,
          useAudioOutput: true,
          useChime: true,
          timer: 3000,
          myMagicWord: false,
          //Your prefer sound play program.
          //By example, if you are running this on OSX, `afplay` could be available.
          //by default mpg321 play program is enabled
          //if audio output cutting try with mpg123 or cvlc program
          playProgram: "mpg321",
          chime: {
            beep: "beep.mp3",
            error: "error.mp3",
            continue: "continue.mp3",
            open: "Google_beep_open.mp3",
            close: "Google_beep_close.mp3",
          },
          // false - animated icons, 'standby' - static icons only for standby state, true - all static icons
          useStaticIcons: false
        },
        micConfig: { // put there configuration generated by auto-installer
          recorder: "arecord",
          device: "plughw:1",
        },
        customActionConfig: {
          autoMakeAction: false,
          autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
          actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
        },
        notifications: {
                ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
                ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
        },
        recipes: ["with-MMM-Hotword.js"],
        profiles: {
          "default": {
            lang: "es-ES"
          }
        },
        addons: false,
      }
    },
    {
      module: "MMM-Hotword",
      position: "top_left",
      config: {
        chimeOnFinish: null,
        mic: {
          recordProgram: "arecord",
          device: "plughw:1",
          sampleRate    : 16000,  // audio sample rate
          channels      : 1,      // number of channels
          threshold     : 0.5,
          thresholdStart: null,
          thresholdEnd  : null,
          silence       : 1.0, // detect end of your hotword or afterRecord.
          verbose       : false,  // log info to the console
        },
        models: [
          {
            hotwords    : "jarvisM",
            file        : "Jarvis_N.pmdl",
            sensitivity : "0.5",
          },
        ],
        commands: {
  				"jarvisM": {
  					notificationExec: {
  						notification: "ASSISTANT_ACTIVATE",
  						payload: (detected, afterRecord) => {
  							return {profile:"default"}
  						}
  					},
  					restart:false,
  					afterRecordLimit:0
  				}
  			}
      }
    }

I hope you can help me. Thanks for all.

**Comment by idmarco** [comment]
I tested with: recipes: ["with-AMk2v3_Jarvis.js"] and then, works fine.
I have modified the file with-AMk2v3_Jarvis.js with my pmdl and it also works.
The config file is incorrect?

**Comment by eouia** [comment]
```js
notification: "ASSISTANT_ACTIVATE",
payload: (detected, afterRecord) => {
return {profile:"default"}
}
```
This is for old version.

**Comment by bugsounet** [comment]
hi, i think you have updated your configuration.
reopen issue, if problem
