### ISSUE TITLE
I want to control my home lights via assistant

### ISSUE THREAD

**Issue by S-Huzaifa** [bugsounet/MMM-AssistantMk2#353]
Hey eouia,
I have little information about python please tell me completely.
What modules and recipes I need for that.
Please reply hurry how can I want to control my home lights via assistant.

**Comment by JohnLucaJF** [comment]
What are your home lights ? i have philips hue and can tell assistant to turn off and on with no problem.

**Comment by S-Huzaifa** [comment]
How you do it? What GPIO pins you use.
What card you use?

**Comment by eouia** [comment]
@S-Huzaifa 
What device do you have? Do you have GPIO-controlled light bulb? (I haven't seen like that before)

**Comment by S-Huzaifa** [comment]
Eouia I havn't any device.I want to use MMM AssistantMk2 OR Gassitpi to turn on light and connect card or device to raspberry pi GPIO.
Like ESP8266

**Comment by eouia** [comment]
If you have already shell script/python program to control your external device, possible. Anyway, you have not any device yet, so after getting one, ask me again.

**Comment by wlmqpsc** [comment]
When you have smart tings, and esp
8266 device. You can try Home Assistant to connect them. Than connect the HA with Google Home. So that you can use Google 
 assistant to control them.

**Comment by JohnLucaJF** [comment]
As to above , then you can add mmm-homeassistant-sensors (make sure U get latest ) to your mirror and your be able to display status as well.

**Comment by bugsounet** [comment]
> Anyway, you have not any device yet, so after getting one, ask we again.
