### ISSUE TITLE
Displaying Images and YouTube

### ISSUE THREAD

**Issue by mattx38** [bugsounet/MMM-AssistantMk2#355]
How can the Assistant could display images and YouTube videos when I say "Jarvis, show me pictures of lions" or "Jarvis, show me the video clip of Nothing else matters on YouTube" ?

**Comment by eouia** [comment]
Use @bugsounet 's addon `Assistant2Display`.

**Comment by mattx38** [comment]
Ok, it works for the images, but not for YouTube

**Comment by bugsounet** [comment]
if don't work, report to authors of Assistant2Display

euh ... ? It's us ;)

**Comment by bugsounet** [comment]
resolved in MMM-Assistant2Display issue.
MMM-YouTube or MMM-Assistant2Display and remote-control module is not compatible.
