### ISSUE TITLE
Getting a "configuration not working" error when trying to test microphone on aiy kit

### ISSUE THREAD

**Issue by Ryan5374** [bugsounet/MMM-AssistantMk2#360]
It gives me that error and asks me to select a card and device. I select the only card and device available and just keeps bringing up that error

**Comment by eouia** [comment]
Detail information(log, your current configs, etc.) is needed to look inside.

**Comment by bugsounet** [comment]
hi, we need more information for help you...

**Comment by robotroot** [comment]
hi, same for me. When I configure "Snowboy" it asks me to configure my audio and when I test my  speakers it gives me this : "Current configuration not working !" . Then I select my only device who works : "Selection of the speaker device
carte 0: ALSA [bcm2835 ALSA], périphérique 0: bcm2835 ALSA [bcm2835 ALSA]
carte 0: ALSA [bcm2835 ALSA], périphérique 1: bcm2835 IEC959/HDMI [bcm2835 IEC959/HDMI]
carte 0: ALSA [bcm2835 ALSA], périphérique 2: bcm2835 IEC959/HDMI1 [bcm2835 IEC959/HDMI1]
carte 1: Sound [HyperX Virtual Surround Sound], périphérique 0: USB Audio [USB Audio]
Indicate the card # to use [0-9]: 1
Indicate the device # to use [0-9]: 0"
After that I try again and I still have "Current configuration not working !" . But when I record my microphone it works.
When I ask my magic mirror it works but I can't hear the answer.

Any ideas to solve this ? 
Thank you

**Comment by bugsounet** [comment]
if mic working and if you ear no response
try this:

```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
mpg321 resources/beep.mp3
```
if you ear sound configure MMM-AssistantMk2 with option `useHTML5: false`
if not work, let's configure your `.asoundrc` file

**Comment by robotroot** [comment]
So it works when I do "useHTML5: false"

Thank you.

**Comment by robotroot** [comment]
But now, when I ask about the weather, I get the answer, I can hear it, however I get redirected on the weather's page and I can't go back to my magic mirror.

can I solve it ?
