### ISSUE TITLE
Can't install grpc and Google assistant dependencies

### ISSUE THREAD

**Issue by JoranK** [bugsounet/MMM-AssistantMk2#361]
**Describe the problem**
After typing "npm install" in the MMM-AssistantMk2 directory, it fails with "Segmentation Fault. ] - fetchMetadata: sill pacote ..." (what's after that is different each time). After running npm-install-que it shows that both dependencies grpc and Google Assistant fail.

**To Reproduce**
Install raspbian buster (on virtualbox to test)
Install npm and nodejs latest version
Install MagicMirror 2.11.0 (config.js and such as well)
Install MMM-Hotword first
Clone MMM-AssistantMk2 into modules folder, cd to folder, npm install. Also tried the manual installtion, with same result.

**Expected behavior**
No fails and a succesful installation

**Environment:**
 - Device :  Virtual machine in virtualbox
 - OS: Raspbian Buster
 - Node Version : 10.15.2
 - npm version: 6.14.4

**Extra info:**
No other modules installed, other than MMM-hotword, which installed fine.

**Comment by bugsounet** [comment]
hi, can you show me errors when it failed on install ?

**Comment by JoranK** [comment]
> hi, can you show me errors when it failed on install ?

Hey, thanks for the reply. I don't seem to get any specific errors, this is the result of npm-install-que:
pastebin.com/rRMJz8Dt

**Comment by bugsounet** [comment]
can you try simply with this:
```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm install
```

**Comment by JoranK** [comment]
> can you try simply with this:
> 
> ```shell
> cd ~/MagicMirror/modules/MMM-AssistantMk2
> npm install
> ```

I only get the Segmentation fault message when I do that:
https://puu.sh/Fw8IA.png

`Segmentation fault.] | fetchMetadata: sill pacote range manifest for protobufjs`

But the end can be different once I enter npm install again:
https://puu.sh/Fw8KT.png

**Comment by bugsounet** [comment]
I suspect raspberry@virtualbox work in x86

Eventually install Debian in virtual box x64 and retry

I use it for my dev

**Comment by JoranK** [comment]
> I suspect raspberry@virtualbox work in x86
> 
> Eventually install Debian in virtual box x64 and retry
> 
> I use it for my dev

Mine is also running on 64-bit (see here: https://puu.sh/Fw8VA.png). I used the Raspbian buster .iso to install it (https://www.raspberrypi.org/downloads/raspberry-pi-desktop/).

**Comment by JoranK** [comment]
Do you perhaps have a Raspbian stretch ISO file? I can't seem to find the old ISO files, only IMG files.

**Comment by bugsounet** [comment]
You have a better compatibility with linux debian x64

Just because raspbian is Debian based

I never install with success Amk2 with raspbian@virtualbox

So, Try with it

**Comment by JoranK** [comment]
> You have a better compatibility with linux debian x64
> 
> Just because raspbian is Debian based
> 
> I never install with success Amk2 with raspbian@virtualbox
> 
> So, Try with it

Ah I see, I will try Debian instead of Raspbian then and report back if it worked.

**Comment by bugsounet** [comment]
I have developped amk2 with it

**Comment by JoranK** [comment]
> I have developped amk2 with it

Which Debian version did you use?

**Comment by bugsounet** [comment]
Buster amd64

**Comment by JoranK** [comment]
> Buster amd64

Thanks for helping, got it installed properly now on Debian Buster x64.
