### ISSUE TITLE
Problème fichier Config.js

### ISSUE THREAD

**Issue by Kevinbad56** [bugsounet/MMM-AssistantMk2#362]
Bonjour,
Tout d'abord merci pour le travail fournit.
Je rencontre un problème au moment d'inscrire le code de configuration du module dans le fichier config.js.
Je copie colle ce qui est indiqué dans le guide. mais cela m'indique le message comme quoi il y'a une erreur avec le fichier config.
Lorsque j'efface ce bloque de code le MM fonctionne correctement.
Merci pour l'aide apporter.

**Comment by bugsounet** [comment]
Bonjour, pouvez-vous me montrer votre fichier de configuration que je le corrige ?

**Comment by Kevinbad56** [comment]
Bonjour merci pour votre intérêt.
A force de recherche j'ai trouvé une erreur dans mon chier configuration. Le MM fonctionne de nouveau. Mais je n'arrive toujours pas à faire fonctionner le module AssistantMK2. En effet je démarre mon MM et la je peux l'utiliser une fois mais je ne peux plus l'utiliser après. Si je recharge avec Ctrl R (recharger MM) alors je peux le réutiliser une fois et ainsi de suite... Penser vous que cela soit du à une erreur de ma part?
merci
[config.txt](https://github.com/bugsounet/MMM-AssistantMk2/files/4464909/config.txt)

**Comment by bugsounet** [comment]
Je vais regarder votre fichier de config dès que je serai chez moi car avec le téléphone c'est pas évident ;)

Je reviens vers vous dès que possible

**Comment by Kevinbad56** [comment]
Merci beaucoup pour votre réactivité.
Je suis novice en la matière j'ai probablement fait une erreur bête. C'est dommage parce que hormis le fait que ne puisse l'utiliser qu'une fois cela marche parfaitement.
Merci à vous

**Comment by bugsounet** [comment]
bonjour, j'ai inspecté votre fichier.
pas de souci de configuration, vous avez bien suivi les consignes ;)

Le souci viens de moi, j'ai simplement oublier de préciser qu'il faut activer `useA2D: true`
dans le fichier de configuration de `MMM-AssistantMk2`

j'ai donc corrigé les wiki et readme correspondant

**Comment by Kevinbad56** [comment]
Super ça fonctionne parfaitement!!! J avais même réessayé une installe propre mais forcement ça n'avait pas résolu le problème!
Je vais maintenant m’attaquer aux module spotify, yooutube... pour le faire fonctionner avec
Merci encore.

**Comment by bugsounet** [comment]
essayez [MMM-Assistant2Display](https://github.com/bugsounet/MMM-Assistant2Display)

**Comment by Kevinbad56** [comment]
Bonjour,
Parfait merci ça fonctionne.
J'ai une dernière petite question, Comment régler la localisation afin que l'heure, la météo... correspondent au lieu où l'on se trouve?
Merci et bon dimanche

**Comment by bugsounet** [comment]
bonjour, il suffit de configurer correctement le champ `assisantConfig { }`,
vous trouverez de l'aide sur le wiki [ici](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Configuration-Structure)

**Comment by Kevinbad56** [comment]
Merci c'est régler grâce à vos indications. Puis-je encore abuser de votre temps? :-)
J'ai installer le module spotify, tout s'est bien passé (Création app spotify ...) j'ai mis le fichier config, j'ai modifié le pattern comme indiqué, mais quand je lance la recherche, l’assistant me donne en résultat un lien mais spotify ne se lance pas.
Je joins mon fichier config au cas où.
Merci
[config.txt](https://github.com/bugsounet/MMM-AssistantMk2/files/4466471/config.txt)

**Comment by bugsounet** [comment]
remplacez :
`recipes: [ "with-MMM-Hotword.js", "with-MMM-TelegramBot.js" ],`
par
`recipes: [ "with-MMM-Spotify.js" ],`

Notes:
 * `with-MMM-Hotword.js` : préprogrammation pour le programme MMM-Hotword mais vous utilisez `MMM-Snowboy`
donc pas utilise vous pouvez le supprimer
 * `with-MMM-TelegramBot.js`: preprogrammation pour le programme `MMM-TelegramBot`, également non utilisé donc vous pouvez le supprimer
 * `with-MMM-Spotify.js`: preprogrammation de AMk2 pour `MMM-Spotify`

plus d'information sur ce recipe preparé sur le [wiki](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Prepared-recipes#with-mmm-spotifyjs)

**Comment by Kevinbad56** [comment]
Ah oui d'accord je n'avais pas compris que je devais modifier cela ici je comprends le fonctionnement du coup.
Mais je me rend compte qu'il doit y avoir un soucis avec MMM spotify. Au démarrage de MM le logo s'affiche puis disparait 2 seconde après.

**Comment by bugsounet** [comment]
le module se montre uniquement lors la lecture d'un titre

**Comment by Kevinbad56** [comment]
Ok bon bien j'ai un soucis ailleurs alors...
Quand je fais la commande vocal je n'ai plus le lien qui s affiche mais un son google et rien ne se passe... je vais chercher

**Comment by bugsounet** [comment]
essayer de jouer une musique avec votre tel,
` MMM-Spotify` devrait s'afficher si la configuration est correcte

**Comment by Kevinbad56** [comment]
Oui ca fonctionne bien ca

**Comment by bugsounet** [comment]
je crois que j'ai vu passer un mail disant que @eouia (co-Programmer de AMk2) devrai regarder au module car il y avait un probleme avec MMM-Spotify au niveau des liens playlist

j'ai pas inspecté si c'était correct ou pas.
je vais regarder dans le courant de la semaine prochaine ;)
Je vous tiens au courant

**Comment by Kevinbad56** [comment]
Par contre je viens de remarqué que si je lance de mon téléphone, je peux par exemple mettre en pause par la voix

**Comment by bugsounet** [comment]
oui de mémoire c'est l'envoi de la recherche qui foire suite a la mise jour de MMM-Spotify

**Comment by Kevinbad56** [comment]
Daccord je vais patienter merci

**Comment by bugsounet** [comment]
actuellement, @eouia est malade, de mon côté je m'occupe de A2D, AMk2, Snowboy & co... 
j'ai pas acces pour regarder/modifier le code de Spotify ;)
C'est possible que la gestion des liens ont changer, il faut que j'inspecte

Actuellement, je suis en train de bosser sur A2D j'essai de faire un module TV et un module Radio

**Comment by Kevinbad56** [comment]
Pas de soucis c'est déjà énorme le travail que vous accomplissez ainsi que votre disponibilité. Je vous remercie. Si j'avais les compétences je n'hésiterai pas à aider si je le pouvais mis je débute et c'est pas facile pour moi lol

**Comment by bugsounet** [comment]
en tout cas merci ;)

ne vous en faite pas, en cas de souci, on est la et on essaye de corriger si besoin ou d'aider un maximum

ps: c'est rare d'avoir un développeur français :p
