### ISSUE TITLE
AssistantMk2 not appearing in my MM

### ISSUE THREAD

**Issue by Kentipi** [bugsounet/MMM-AssistantMk2#364]
Successful install, verified with node auth_and_test.js. Audio check Ok. Simple config from github placed in my config.js
MMM-AssistantMk2.js is edited with my projectId.
Reboot and npm start, but no assistant logo, no response from assistant.

**Environment:**
 - Device : MacBookAir running Ubuntu
 - Node Version : Can't find it...how..?

Installed as instructed with automatic process.

Not using pm2. When running npm start npm dev it seems like AssistantMk2 is running but cant see it anywhere on the screen, nor get any feedback from wakewords such as hi google, ok google, or jarvis

**Comment by eouia** [comment]
Show me your config and logs.
And AMK2 should be awakened by notification from other modules to be started.

**Comment by Kentipi** [comment]
My config (i've x-ed out my private calender adress and the identity of my local busstop.

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "nb",
	timeFormat: 24,
	units: "metric",

	modules: [

		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},

		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Planlagte hendelser",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/xxxxxxxxxxxxx%40gmail.com/private-xxxxxxxxxxxb3e07ce082154c6cdc9/basic.ics"					}
				]
			}
		},
{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    ui: "Fullscreen",
    assistantConfig: {
      latitude: 51.508530,
      longitude: -0.076132,
    },
    micConfig: { 
      recorder: "arecord",
      device: "plughw:0",
    },
    recipes: [ "with-MMM-Hotword.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    useA2D: false,
  }
},

{
        module: "MMM-Entur-tavle",
        position: "lower_third",
        config: {
            stopId: 'xxxxx',
            stopType: 'StopPlace',
            numResults: 5,
            showName: true,
            highlightRealtime: true,
            delay: [5, 'minutes'],
        }
    },

		,
		{
	module: 'MMM-YrThen',
	position: 'top_right',
	config: {
		location: '10-1014992',
	}
},

		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "NRK Nyheter",
						url: "https://www.nrk.no/nyheter/siste.rss"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]
  

 

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by Kentipi** [comment]
Should mention I've tried AssistantMk2 position as default fullscreen before I set it to top_right

**Comment by Kentipi** [comment]
MagicMirror$ npm run config:check

Line 54 col 1 Expected indentation of 2 tabs but found 0.
Line 55 col 1 Expected indentation of 3 tabs but found 2 spaces.
Line 56 col 1 Expected indentation of 3 tabs but found 2 spaces.
Line 57 col 1 Expected indentation of 3 tabs but found 2 spaces.
Line 58 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 59 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 60 col 1 Expected indentation of 5 tabs but found 6 spaces.
Line 61 col 1 Expected indentation of 5 tabs but found 6 spaces.
Line 62 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 63 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 63 col 17 Trailing spaces not allowed.
Line 64 col 1 Expected indentation of 5 tabs but found 6 spaces.
Line 65 col 1 Expected indentation of 5 tabs but found 6 spaces.
Line 66 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 67 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 68 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 69 col 1 Expected indentation of 5 tabs but found 6 spaces.
Line 70 col 1 Expected indentation of 6 tabs but found 8 spaces.
Line 71 col 1 Expected indentation of 6 tabs but found 8 spaces.
Line 72 col 1 Expected indentation of 5 tabs but found 6 spaces.
Line 73 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 74 col 1 Expected indentation of 4 tabs but found 4 spaces.
Line 75 col 1 Expected indentation of 3 tabs but found 2 spaces.
Line 76 col 1 Expected indentation of 2 tabs but found 0.
Line 78 col 1 Expected indentation of 2 tabs but found 0.
Line 79 col 1 Expected indentation of 3 tabs but found 8 spaces.
Line 80 col 1 Expected indentation of 3 tabs but found 8 spaces.
Line 81 col 1 Expected indentation of 3 tabs but found 8 spaces.
Line 82 col 1 Expected indentation of 4 tabs but found 12 spaces.
Line 82 col 21 Strings must use doublequote.
Line 83 col 1 Expected indentation of 4 tabs but found 12 spaces.
Line 83 col 23 Strings must use doublequote.
Line 84 col 1 Expected indentation of 4 tabs but found 12 spaces.
Line 85 col 1 Expected indentation of 4 tabs but found 12 spaces.
Line 86 col 1 Expected indentation of 4 tabs but found 12 spaces.
Line 87 col 1 Expected indentation of 4 tabs but found 12 spaces.
Line 87 col 24 Strings must use doublequote.
Line 88 col 1 Expected indentation of 3 tabs but found 8 spaces.
Line 89 col 1 Expected indentation of 2 tabs but found 4 spaces.
Line 93 col 1 Expected indentation of 3 tabs but found 1.
Line 93 col 10 Strings must use doublequote.
Line 94 col 1 Expected indentation of 3 tabs but found 1.
Line 94 col 12 Strings must use doublequote.
Line 95 col 1 Expected indentation of 3 tabs but found 1.
Line 96 col 1 Expected indentation of 4 tabs but found 2.
Line 96 col 13 Strings must use doublequote.
Line 97 col 1 Expected indentation of 3 tabs but found 1.
Line 98 col 1 Expected indentation of 2 tabs but found 0.
Line 117 col 1 Trailing spaces not allowed.
Line 118 col 1 More than 1 blank line not allowed.
Line 119 col 1 Trailing spaces not allowed.

**Comment by eouia** [comment]
I need runtime log to see what happened. `npm run config:check` is something to find syntax error on your configuration.

**Comment by eouia** [comment]
And you included `with-MMM-Hotword.js` but there seems no MMM-Hotword configuration in your config.js.

**Comment by Kentipi** [comment]
I'm a complete n00b. I can produce a runtime log using jslint or is another way better? what command should I run?

**Comment by eouia** [comment]
You can use log of `pm2`, but I recommend you this;
- stop pm2 (If you are using)
- Go to MagicMirror directory
- Execute `npm start dev`

Before; I recommend you remove (or comment out or set `disabled:true`) all other modules from config.js to make things simple. Leave only MMM-AssistantMk2, MMM-Hotword and clock module.

**Comment by Kentipi** [comment]
Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/en.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/default/alert//alert.js
module.js:479 Module registered: alert
loader.js:150 Bootstrapping module: alert
loader.js:179 Load script: modules/default/alert/classie.js
loader.js:179 Load script: modules/default/alert/modernizr.custom.js
loader.js:179 Load script: modules/default/alert/notificationFx.js
loader.js:155 Scripts loaded for: alert
loader.js:194 Load stylesheet: modules/default/alert/ns-default.css
loader.js:194 Load stylesheet: vendor/css/font-awesome.css
loader.js:157 Styles loaded for: alert
translator.js:175 alert - Load translation fallback: translations/en.json
/home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
  protocols.This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/default/alert//alert.js
- http://localhost:8080/modules/default/alert/classie.js
- http://localhost:8080/modules/default/alert/modernizr.custom.js
- http://localhost:8080/modules/default/alert/notificationFx.js
- http://localhost:8080/modules/default/alert/ns-default.css
- http://localhost:8080/vendor/css/font-awesome.css
- http://localhost:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/all.min.css
- http://localhost:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/v4-shims.min.css
  
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95
/home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
(anonymous) @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145
loader.js:159 Translations loaded for: alert
loader.js:179 Load script: modules/default/updatenotification//updatenotification.js
module.js:479 Module registered: updatenotification
loader.js:150 Bootstrapping module: updatenotification
loader.js:155 Scripts loaded for: updatenotification
loader.js:157 Styles loaded for: updatenotification
loader.js:159 Translations loaded for: updatenotification
loader.js:179 Load script: modules/default/clock//clock.js
module.js:479 Module registered: clock
loader.js:150 Bootstrapping module: clock
loader.js:179 Load script: vendor/node_modules/moment/min/moment-with-locales.js
loader.js:179 Load script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
loader.js:179 Load script: vendor/node_modules/suncalc/suncalc.js
loader.js:155 Scripts loaded for: clock
loader.js:194 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:157 Styles loaded for: clock
loader.js:159 Translations loaded for: clock
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:479 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: /modules/MMM-AssistantMk2/library/response.class.js
loader.js:179 Load script: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
translator.js:175 MMM-AssistantMk2 - Load translation fallback: translations/en.json
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:179 Load script: modules/MMM-Hotword//MMM-Hotword.js
module.js:479 Module registered: MMM-Hotword
loader.js:150 Bootstrapping module: MMM-Hotword
loader.js:179 Load script: https://code.iconify.design/1/1.0.2/iconify.min.js
loader.js:155 Scripts loaded for: MMM-Hotword
loader.js:194 Load stylesheet: modules/MMM-Hotword/MMM-Hotword.css
loader.js:157 Styles loaded for: MMM-Hotword
loader.js:159 Translations loaded for: MMM-Hotword
loader.js:194 Load stylesheet: css/custom.css
alert.js:153 Starting module: alert
updatenotification.js:14 Start updatenotification
clock.js:45 Starting module: clock
main.js:474 All modules started!

**Comment by Kentipi** [comment]
BTW this is the config settings:

modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},

		{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    ui: "Fullscreen",
    assistantConfig: {
      latitude: 51.508530,
      longitude: -0.076132,
    },
    micConfig: { 
      recorder: "arecord",
      device: "plughw:0",
    },
    recipes: [ "with-MMM-Hotword.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    useA2D: false,
  }
},

{
  module: "MMM-Hotword",
  position: "top_right",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:0"
    },
    models: [
      {
        hotwords    : "jarvis",
        file        : "jarvis.umdl",
        sensitivity : "0.5",
      },
    ],
    commands: {
      "jarvis": {
        notificationExec: {
          notification: "TEST",
        },
        restart:false,
        afterRecordLimit:0
      }
    }
},

		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by Kentipi** [comment]
![MM](https://user-images.githubusercontent.com/63724246/79447536-4e394780-7fe0-11ea-85fa-1bfd13f61c87.png)

**Comment by bugsounet** [comment]
hi,
humm... you do read [wiki installation guide](https://github.com/bugsounet/MMM-AssistantMk2/wiki) ?

1) Fullscreen ui have not screen icon (popup displaying on activating)
define another ui for icon displaying
2) Read wiki for configuring your activator (MMM-Hotword or MMM-Snowboy)

let's retry with it ;)

**Comment by Kentipi** [comment]
ok.. Now I did this in my config.js

{
  module: "MMM-AssistantMk2",
  position: "fullscreen_above",
  config: {
    ui: "Fullscreen",
    assistantConfig: {
      latitude: 51.508530,
      longitude: -0.076132,
    },
    micConfig: { 
      recorder: "arecord",
      device: "plughw:0",
    },
    recipes: [ "with-MMM-Hotword.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    useA2D: false,
  }
},

{
    module: "MMM-Hotword",
    position: "bottom_left",
    config: {
      useDisplay: false,
      chimeOnFinish: null,
      recipes: ["with-AMk2v3_smart-mirror.js"],
      mic: {
        recordProgram: "arecord",
        device: "plughw:0",
      },
    },
  },

It responds to "Smart Mirror" command, but instantly shows "Sorry I don't understand"

**Comment by Kentipi** [comment]
Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/en.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/default/alert//alert.js
module.js:479 Module registered: alert
loader.js:150 Bootstrapping module: alert
loader.js:179 Load script: modules/default/alert/classie.js
loader.js:179 Load script: modules/default/alert/modernizr.custom.js
loader.js:179 Load script: modules/default/alert/notificationFx.js
loader.js:155 Scripts loaded for: alert
loader.js:194 Load stylesheet: modules/default/alert/ns-default.css
loader.js:194 Load stylesheet: vendor/css/font-awesome.css
loader.js:157 Styles loaded for: alert
translator.js:175 alert - Load translation fallback: translations/en.json
/home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
  protocols.This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/default/alert//alert.js
- http://localhost:8080/modules/default/alert/classie.js
- http://localhost:8080/modules/default/alert/modernizr.custom.js
- http://localhost:8080/modules/default/alert/notificationFx.js
- http://localhost:8080/modules/default/alert/ns-default.css
- http://localhost:8080/vendor/css/font-awesome.css
- http://localhost:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/all.min.css
- http://localhost:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/v4-shims.min.css
  
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95
logSecurityWarnings @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:214
loadHandler @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:233
/home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
(anonymous) @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145
Promise.then (async)
warnAboutInsecureCSP @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:139
logSecurityWarnings @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:218
loadHandler @ /home/kentshala/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:233
loader.js:159 Translations loaded for: alert
loader.js:179 Load script: modules/default/updatenotification//updatenotification.js
module.js:479 Module registered: updatenotification
loader.js:150 Bootstrapping module: updatenotification
loader.js:155 Scripts loaded for: updatenotification
loader.js:157 Styles loaded for: updatenotification
loader.js:159 Translations loaded for: updatenotification
loader.js:179 Load script: modules/default/clock//clock.js
module.js:479 Module registered: clock
loader.js:150 Bootstrapping module: clock
loader.js:179 Load script: vendor/node_modules/moment/min/moment-with-locales.js
loader.js:179 Load script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
loader.js:179 Load script: vendor/node_modules/suncalc/suncalc.js
loader.js:155 Scripts loaded for: clock
loader.js:194 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:157 Styles loaded for: clock
loader.js:159 Translations loaded for: clock
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:479 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: /modules/MMM-AssistantMk2/library/response.class.js
loader.js:179 Load script: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
translator.js:175 MMM-AssistantMk2 - Load translation fallback: translations/en.json
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:179 Load script: modules/MMM-Hotword//MMM-Hotword.js
module.js:479 Module registered: MMM-Hotword
loader.js:150 Bootstrapping module: MMM-Hotword
loader.js:155 Scripts loaded for: MMM-Hotword
loader.js:194 Load stylesheet: modules/MMM-Hotword/MMM-Hotword.css
loader.js:157 Styles loaded for: MMM-Hotword
loader.js:159 Translations loaded for: MMM-Hotword
loader.js:194 Load stylesheet: css/custom.css
alert.js:153 Starting module: alert
updatenotification.js:14 Start updatenotification
clock.js:45 Starting module: clock
main.js:474 All modules started!
MMM-Hotword.js:205 [HOTWORD] Command is excuting
MMM-Hotword.js:215 [HOTWORD] notificationExec: ASSISTANT_ACTIVATE {profile: "default", type: "MIC"}
module.js:198 alert is suspended.
module.js:198 clock is suspended.
module.js:198 MMM-Hotword is suspended.
module.js:205 alert is resumed.
module.js:205 clock is resumed.
module.js:205 MMM-Hotword is resumed.

![jarvis test](https://user-images.githubusercontent.com/63724246/79453941-affeaf00-7fea-11ea-910a-4d883f059d13.png)

**Comment by Kentipi** [comment]
![jarvis failed](https://user-images.githubusercontent.com/63724246/79454162-0b30a180-7feb-11ea-8604-a3ba9e8f3307.png)

**Comment by Kentipi** [comment]
NVM! got it working using a diffenrent credentials.json file from a previous project that I new worked.
Thank you for all your help! really awesome!

**Comment by bugsounet** [comment]
humm ...
for this problem ... what's wiki says...

i see in [this](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Configuration-Sample#use-with-mmm-hotword) place


**Notes:**

In v3 of AMk2, hotword not works like V2: you have just to say `smart mirror, what time is it ?`

In a short delay time (1 second) AMk2 will respond.

You don't have to wait to a confirm beep !
Hotword send directly your request `what time is it ?`

If your environement is so noisy, Hotword can take a long time to activate AMk2
and if your request is null (if you just say `smart mirror`)

AMk2 v3 can reply if your environnement is noisy `Sorry I don't understand`

If you don't like this feature or noisy environement, we prepared recipes for this
* `with-AMk2v3-noisy_smart-mirror.js` for smart mirror keyword

* `with-AMk2v3-noisy_Jarvis.js` for Jarvis keyword

With noisy recipes you have now activator like AMk2 v2

**Comment by Kentipi** [comment]
So.... I messed up. I made too many changes without a backup of my config.js.....so I'm back to the beginning. Lesson learned. I'll always copy the file and move to a backup folder before any changes are made....
This is my config setup, but all i get is "make a config file"
modules: [
{
  module: "MMM-AssistantMk2",
  position: "fullscreen_above",
  config: {
    ui: "Classic",
    assistantConfig: {
      latitude: 51.508530,
      longitude: -0.076132,
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:0",
    },
    recipes: [ "with-MMM-Hotword.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    useA2D: false,
  }
},

{
  module: "MMM-Hotword",
  position: "bottom_left",
   config: {
    useDisplay: false,
    chimeOnFinish: null,
    recipes: ["with-AMk2v3_smart-mirror.js"],
    mic: {
      recordProgram: "arecord",
      device: "plughw:0",
    },
  },
},
/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by bugsounet** [comment]
and so ? what can i do ?

**Comment by Kentipi** [comment]
I've tried with hotword module only, then it works. With assistantmk2 module only it doesn't. So the error is somewhere in that module, but I cannot for the life of me understand why, especially since I have only copy pasted from wiki (and added recipe to use hotword module) can you (or anybody) verify that wiki version works with latest update?

**Comment by bugsounet** [comment]
wiki is up to date,
so i think you have make a mismake somewhere ...
what console says when you start MM with `mpm start`
(of course if you use `pm2` : stop the process)
```sh
cd ~/MagicMirror
npm start
```
