### ISSUE TITLE
Problème mise a jour.

### ISSUE THREAD

**Issue by Kevinbad56** [bugsounet/MMM-AssistantMk2#367]
Bonjour,
Je rencontre des difficultés avec la mise à jour.
Je tape la commande npm run rebuild.
Mais j'obtiens:
npm ERR! missing script: rebuild
Si qulelqu'un connait la source du problème! 
merci à vous

**Comment by bugsounet** [comment]
bonjour,
cette commande est disponible depuis peu.
Il faut donc la derniere mise a jour pour pouvoir l'utiliser
Elle est a utiliser uniquement si probleme réél.
esayez plutot:
`npm run update` d'abord

**Comment by Kevinbad56** [comment]
Merci.
Lorsque je fais cette commande j'obtiens:
> MMM-AssistantMk2@3.2.0 update /home/pi/MagicMirror/modules/MMM-AssistantMk2
> installer/update.sh

sh: 1: installer/update.sh: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! MMM-AssistantMk2@3.2.0 update: `installer/update.sh`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the MMM-AssistantMk2@3.2.0 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-17T13_34_56_567Z-debug.log

**Comment by bugsounet** [comment]
ah ...
j'ai du oublier de mettre une permission
```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2/installer
chmod +x update.sh
cd ..
npm run update
```

**Comment by Kevinbad56** [comment]
Toujours aussi réactif ;-).
J'ai réaliser la manip. mais came donne ca:
> MMM-AssistantMk2@3.2.0 update /home/pi/MagicMirror/modules/MMM-AssistantMk2
> installer/update.sh

Welcome to AMk2 updater !

Updating...
Mise à jour 230053b..eeecb9e
error: Vos modifications locales aux fichiers suivants seraient écrasées par la fusion :
	File_translations/Chinese_simplified/README_zh-CN.md
	File_translations/Chinese_simplified/wiki/Configuration-Sample.md
	File_translations/Chinese_simplified/wiki/Configuration-Structure.md
	File_translations/Chinese_simplified/wiki/Google-Assistant-Setup.md
	File_translations/Chinese_simplified/wiki/Home.md
	File_translations/Chinese_simplified/wiki/Installation.md
	File_translations/Chinese_simplified/wiki/MagicMirror-volume-level.md
	File_translations/Chinese_simplified/wiki/Notifications.md
	File_translations/Chinese_simplified/wiki/Prepared-recipes.md
	File_translations/Chinese_simplified/wiki/Recipes.md
	File_translations/Chinese_simplified/wiki/Register-your-Mirror-as-Google-Assistant-related-device.md
	File_translations/Chinese_simplified/wiki/Resolving-mmap-issue-and-no-response-audio.md
	File_translations/Chinese_simplified/wiki/Self-check-for-issue.md
	File_translations/Chinese_simplified/wiki/action.md
	File_translations/Chinese_simplified/wiki/commands.md
	File_translations/Chinese_simplified/wiki/myMagicWord.md
	File_translations/Chinese_simplified/wiki/plugins.md
	File_translations/Chinese_simplified/wiki/responseHooks.md
	File_translations/Chinese_simplified/wiki/transcriptionHooks.md
	installer/dev.sh
	installer/master.sh
Veuillez valider ou remiser vos modifications avant la fusion.
Abandon
Installing...

> MMM-AssistantMk2@3.2.0 postinstall /home/pi/MagicMirror/modules/MMM-AssistantMk2
> installer/postinstall.sh

sh: 1: installer/postinstall.sh: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! MMM-AssistantMk2@3.2.0 postinstall: `installer/postinstall.sh`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the MMM-AssistantMk2@3.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-17T13_42_33_533Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! MMM-AssistantMk2@3.2.0 update: `installer/update.sh`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the MMM-AssistantMk2@3.2.0 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-17T13_42_33_986Z-debug.log

**Comment by bugsounet** [comment]
Il y a quelque chose de bizzare...

esayez ceci : 
```sh
cd ~MagicMirror/modules/MMM-AssistantMk2
ls -la
```
et donnez moi le résultat

**Comment by Kevinbad56** [comment]
total 128
drwxr-xr-x  15 pi pi  4096 avril 17 15:52 .
drwxr-xr-x  10 pi pi  4096 avril 17 13:56 ..
-rw-r--r--   1 pi pi  2028 avril 12 00:50 auth_and_test.js
drwxr-xr-x   2 pi pi  4096 avril 17 13:49 components
-rw-r--r--   1 pi pi   427 avril 11 14:36 credentials.json
-rw-r--r--   1 pi pi   132 avril 12 00:50 deviceInstance.sample.json
drwxr-xr-x   3 pi pi  4096 avril 17 13:49 File_translations
drwxr-xr-x   8 pi pi  4096 avril 17 15:52 .git
drwxr-xr-x   3 pi pi  4096 avril 17 13:49 .github
-rw-r--r--   1 pi pi   739 avril 12 00:50 .gitignore
drwxr-xr-x   2 pi pi  4096 avril 17 13:49 installer
drwxr-xr-x   3 pi pi  4096 avril 17 13:49 library
-rw-r--r--   1 pi pi  1073 avril 12 00:50 LICENSE
-rw-r--r--   1 pi pi 21439 avril 12 00:50 MMM-AssistantMk2.js
-rw-r--r--   1 pi pi  7227 avril 12 00:50 node_helper.js
drwxr-xr-x 199 pi pi  4096 avril 17 15:30 node_modules
-rw-r--r--   1 pi pi  1036 avril 17 15:52 package.json
drwxr-xr-x   2 pi pi  4096 avril 17 13:56 profiles
-rw-r--r--   1 pi pi  4249 avril 12 00:50 README.md
drwxr-xr-x   2 pi pi  4096 avril 17 13:56 recipes
drwxr-xr-x   2 pi pi  4096 avril 17 13:56 resources
drwxr-xr-x   2 pi pi  4096 avril 17 15:31 tmp
drwxr-xr-x   2 pi pi  4096 avril 17 13:56 translations
drwxr-xr-x   5 pi pi  4096 avril 17 13:56 ui
-rw-r--r--   1 pi pi    25 avril 12 00:50 update

**Comment by bugsounet** [comment]
parfait:

essayez dans le repertoire AMk2
```sh
git pull
```
et coller moi le résultat

**Comment by Kevinbad56** [comment]
Mise à jour 230053b..eeecb9e
error: Vos modifications locales aux fichiers suivants seraient écrasées par la fusion :
	File_translations/Chinese_simplified/README_zh-CN.md
	File_translations/Chinese_simplified/wiki/Configuration-Sample.md
	File_translations/Chinese_simplified/wiki/Configuration-Structure.md
	File_translations/Chinese_simplified/wiki/Google-Assistant-Setup.md
	File_translations/Chinese_simplified/wiki/Home.md
	File_translations/Chinese_simplified/wiki/Installation.md
	File_translations/Chinese_simplified/wiki/MagicMirror-volume-level.md
	File_translations/Chinese_simplified/wiki/Notifications.md
	File_translations/Chinese_simplified/wiki/Prepared-recipes.md
	File_translations/Chinese_simplified/wiki/Recipes.md
	File_translations/Chinese_simplified/wiki/Register-your-Mirror-as-Google-Assistant-related-device.md
	File_translations/Chinese_simplified/wiki/Resolving-mmap-issue-and-no-response-audio.md
	File_translations/Chinese_simplified/wiki/Self-check-for-issue.md
	File_translations/Chinese_simplified/wiki/action.md
	File_translations/Chinese_simplified/wiki/commands.md
	File_translations/Chinese_simplified/wiki/myMagicWord.md
	File_translations/Chinese_simplified/wiki/plugins.md
	File_translations/Chinese_simplified/wiki/responseHooks.md
	File_translations/Chinese_simplified/wiki/transcriptionHooks.md
	installer/dev.sh
	installer/master.sh
Veuillez valider ou remiser vos modifications avant la fusion.
Abandon

**Comment by Kevinbad56** [comment]
Je sais pas si j'ai mal fait quelques chose de mal

**Comment by bugsounet** [comment]
bon ... on va le faire a la main...

toujours dans le répertoire de AMk2:
```sh
rm -rf File_translations installer/dev.sh installer/dev.sh
git pull
```

**Comment by Kevinbad56** [comment]
Mise à jour 230053b..eeecb9e
error: Vos modifications locales aux fichiers suivants seraient écrasées par la fusion :
	installer/master.sh
Veuillez valider ou remiser vos modifications avant la fusion.
Abandon

**Comment by bugsounet** [comment]
j'ai editer le post mais il était trop tard ;)

```sh
rm -rf installer/master.sh
git pull
```

**Comment by Kevinbad56** [comment]
:-)
Alors ca me donne ca! cela signifie. que c'est bon?
Mise à jour 230053b..eeecb9e
Fast-forward
 MMM-AssistantMk2.js                                                               |   7 +-
 README.md                                                                         |  23 +++-
 library/response.class.js => components/response.js                               |   1 +
 installer/dev.sh                                                                  |  44 ------
 installer/master.sh                                                               |  43 ------
 installer/rebuild.sh                                                              |  46 +++++++
 installer/update.sh                                                               |   1 +
 library/response.js                                                               |  92 -------------
 library/responseUI/response.example.js                                            |  73 ----------
 package.json                                                                      |  17 +--
 recipes/hide_when_no_use.js                                                       |  59 --------
 recipes/test.js                                                                   |  26 ----
 recipes/with-MMM-NewPIR.js                                                        |  41 ------
 recipes/with-MMM-News.js                                                          |  10 --
 recipes/with-MMM-TelegramBot.js                                                   |   7 -
 recipes/with-MMM-Timetable.js                                                     |  10 --
 recipes/with-radio_fr.js                                                          | 282 +++++++++++++++++++++++++++++++++++++++
 {File_translations => translations}/Chinese_simplified/README_zh-CN.md            |   0
 .../Chinese_simplified/wiki/Configuration-Sample.md                               |   0
 .../Chinese_simplified/wiki/Configuration-Structure.md                            |   0
 .../Chinese_simplified/wiki/Google-Assistant-Setup.md                             |   0
 {File_translations => translations}/Chinese_simplified/wiki/Home.md               |   0
 {File_translations => translations}/Chinese_simplified/wiki/Installation.md       |   0
 .../Chinese_simplified/wiki/MagicMirror-volume-level.md                           |   0
 {File_translations => translations}/Chinese_simplified/wiki/Notifications.md      |   0
 {File_translations => translations}/Chinese_simplified/wiki/Prepared-recipes.md   |   0
 {File_translations => translations}/Chinese_simplified/wiki/Recipes.md            |   0
 .../wiki/Register-your-Mirror-as-Google-Assistant-related-device.md               |   0
 .../Chinese_simplified/wiki/Resolving-mmap-issue-and-no-response-audio.md         |   0
 .../Chinese_simplified/wiki/Self-check-for-issue.md                               |   0
 {File_translations => translations}/Chinese_simplified/wiki/action.md             |   0
 {File_translations => translations}/Chinese_simplified/wiki/commands.md           |   0
 {File_translations => translations}/Chinese_simplified/wiki/myMagicWord.md        |   0
 {File_translations => translations}/Chinese_simplified/wiki/plugins.md            |   0
 {File_translations => translations}/Chinese_simplified/wiki/responseHooks.md      |   0
 {File_translations => translations}/Chinese_simplified/wiki/transcriptionHooks.md |   0
 translations/en.json                                                              |   4 +-
 translations/fr.json                                                              |   4 +-
 38 files changed, 362 insertions(+), 428 deletions(-)
 rename library/response.class.js => components/response.js (99%)
 delete mode 100755 installer/dev.sh
 delete mode 100755 installer/master.sh
 create mode 100755 installer/rebuild.sh
 delete mode 100644 library/response.js
 delete mode 100644 library/responseUI/response.example.js
 delete mode 100644 recipes/hide_when_no_use.js
 delete mode 100644 recipes/test.js
 delete mode 100644 recipes/with-MMM-NewPIR.js
 delete mode 100644 recipes/with-MMM-News.js
 delete mode 100644 recipes/with-MMM-Timetable.js
 create mode 100644 recipes/with-radio_fr.js
 rename {File_translations => translations}/Chinese_simplified/README_zh-CN.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Configuration-Sample.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Configuration-Structure.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Google-Assistant-Setup.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Home.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Installation.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/MagicMirror-volume-level.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Notifications.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Prepared-recipes.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Recipes.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Register-your-Mirror-as-Google-Assistant-related-device.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Resolving-mmap-issue-and-no-response-audio.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/Self-check-for-issue.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/action.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/commands.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/myMagicWord.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/plugins.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/responseHooks.md (100%)
 rename {File_translations => translations}/Chinese_simplified/wiki/transcriptionHooks.md (100%)

**Comment by bugsounet** [comment]
oui mise a jour effectivée avec succès ;)

v3.2.0->v3.2.2

**Comment by Kevinbad56** [comment]
Encore merci pour la réactivité et l'efficacité!
Concernant Assistant2display je dois faire le même genre de manip ou ça se fera bien?

**Comment by bugsounet** [comment]
j'ai pas fait de script special pour le moment
essayez ceci dans A2D
```sh
git pull
npm install
```

**Comment by bugsounet** [comment]
par contre lisez bien le wiki de A2D, il y a des changement pour l'installation
cela dépend de ce que vous utilisez comme modules

**Comment by Kevinbad56** [comment]
Parfait merci pour tout je vais m'y atteler

**Comment by bugsounet** [comment]
pas de souci, en cas de besoin n'hesitez pas a ouvrir une issue ;)
