### ISSUE TITLE
bonjour, divers problèmes

### ISSUE THREAD

**Issue by bigjojo** [bugsounet/MMM-AssistantMk2#368]
bonjour, je me permets d'écrire en francais, merci d'abord pour le travail fourni et toutes les évolutions.

je rencontre quelques soucis.
une question un peu con mais comment fait-on pour stopper la radio quand celle ci est lancé, quel commande.

ensuite un probleme concernant le son, je fonctionnes avec un dongle usb pour connection micro et haut parleur. impossible pour moi de faire changer le son via l'assistant. quel formule choisir entre pulse alsa hors que mon réglage est sur usb device output.

mon autre probleme est pour spotify, lorsque je lance une chanson via mon pc ou gsm vers le miroir, je peux par la suite dire toute les commandes sa passe, mais impossible de lancer directement une chanson par la voix via l'assistant, il m'ouvre une page internet.

merci d'avance pour les réponses apportées.

**Comment by bugsounet** [comment]
bonjour,

> une question un peu con mais comment fait-on pour stopper la radio quand celle ci est lancé, quel commande.

MMM-AssistantMk2 ne gère pas la radio

> ensuite un probleme concernant le son, je fonctionnes avec un dongle usb pour connection micro et haut parleur. impossible pour moi de faire changer le son via l'assistant. quel formule choisir entre pulse alsa hors que mon réglage est sur usb device output.

Je ne comprend pas votre question, car si l'assistant vous entend, et que vous entendez la réponse... c'est que cela fonctionne

> mon autre probleme est pour spotify, lorsque je lance une chanson via mon pc ou gsm vers le miroir, je peux par la suite dire toute les commandes sa passe, mais impossible de lancer directement une chanson par la voix via l'assistant, il m'ouvre une page internet.

je pense que vous n'avez pas lu le wiki concernant [Spotify](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Prepared-recipes#with-mmm-spotifyjs) et le module [MMM-Spotify](https://github.com/eouia/MMM-Spotify)

**Comment by bigjojo** [comment]
re,
le recipe radio fr ne fait pas partie de mk2 ??? ou alors je confonds avec a2d.

concernant spotify, j'ai bien lu le wiki (j'ai bien un compte premium et raspotify) mais je me posais la question pourquoi, si je demande a l'assistant de me jouer tels musique, il ne le lance pas.
mais si je lance une musique sur le miroir via spotify pc ou gsm et que ensuite je demande au miroir de me jouer tel chanson, il l'a recherche et la lance directement.

pour l'audio, je n'ai pas de probleme de reconnaissance ou de son, si ce n'est que lorsque je demande de mettre le volume a 20%, il me répond ok, met ne change pas le volume.

c'est question son peut etre relier a a2d.

merci

**Comment by bugsounet** [comment]
parfait, dans ce cas pas de souci avec MMM-AssistantMk2
