### ISSUE TITLE
안녕하세요. update 관련 문의

### ISSUE THREAD

**Issue by josooik** [bugsounet/MMM-AssistantMk2#369]
안녕하세요. update 관련 문의 드립니다.

Update available for MMM-AssistantMk2 module.

업데이트 하라고 떻는데 제가 기존에 설치된버전 지우고 새로올라온 버전으로 다시 설치해서 업데이트

했는데 매번 업데이트마다 그러기에는 너무 번거러워서 업데이트 관련 명령어가 따로 있나요???

**Comment by bugsounet** [comment]
Hi, sorry can you retry with speaking english ?

**Comment by josooik** [comment]
Hello, I'm inquiring about the update.

Update available for MMM-AssistantMk2 module.

How can I update it by erasing the existing version and reinstalling the updated version?

Do you have any update-related commands because every update is too cumbersome to do that?

**Comment by bugsounet** [comment]
just one thing simple to do:
[Readme](https://github.com/bugsounet/MMM-AssistantMk2#update-from-3x) says :  
```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm run update
```

i will updating and not erasing

**Comment by eouia** [comment]
I think you just better to remove `updatenotification` module. If you are satisfied with your current mirror, you don't need to update.

그냥 `updateNotification` 모듈을 사용하지 마세요. 현재 미러에 불만이 없으시다면 굳이 업데이트 안하셔도 됩니다.
