### ISSUE TITLE
Want to install Alexa 

### ISSUE THREAD

**Issue by p10dulkar** [bugsounet/MMM-AssistantMk2#371]
when I install Google assistantmk2
I am not able to install Alexa it gives an error that device resource is busy or not responding
Do I have to attach one more mic for Alexa or is there any way to work both of them at the same time individually just by saying the hotword

**Comment by bugsounet** [comment]
hi,
MMM-AssistantMk2 use **only** `MIC` when it's activated.
In stand-by mode, the module don't use `MIC`
I think, it's not related to it

**Comment by eouia** [comment]
But, Hotword would listen most time.
If you add an additional one more mic, you can dedicate it to your Alexa.

**Comment by p10dulkar** [comment]
Is there any way hotword can also be activated only when I speak the hotword 
and idle when I don't speak it

**Comment by bugsounet** [comment]
@p10dulkar:
I think it's better to see with your activator module (like MMM-Hotword, MMM-Snowboy, or other)
because it use mic in continous.

in all cases, it's not related with MMM-AssistantMk2
it's not an issue with this module

**Comment by p10dulkar** [comment]
will it work without adding MMM - Hotword like by the default hotword ok google or hey google
