### ISSUE TITLE
기능 문의 드립니다

### ISSUE THREAD

**Issue by Geomke** [bugsounet/MMM-AssistantMk2#372]
음성 인식을 통해 유튜브 영상을 표시를 해보았지만 인터넷 환경에 따라서 영상이 멈추는 현상이 있어서 유튜브가 아닌 라즈베리파이에 저장된 비디오 파일을 음성인식을 통해 불러오고 싶은데 가능한지 문의드립니다
음성인식을 통한 비디오 파일을 매직미러에서 출력하려고 합니다

**Comment by bugsounet** [comment]
hi, for helping, can you try speaking in english please ?

**Comment by eouia** [comment]
AMk2 자체는 Goggle Assistant의 Custom device implement이고, 여기에 사용자 명령어를 추가할 수 있는 기능을 넣은 모듈입니다. 따라서, 실제로 해야 하는 작업은 그걸 해줄 수 있는 모듈을 별도로 필요로 하죠. 
말씀하신 기능은 "라즈베리 파이에 저장된 동영상을 매직미러 스크린에 출력하는 모듈"이 있다면 가능합니다. 그런 모듈을 찾으시거나, 직접 만드시면 되겠죠.

**Comment by bugsounet** [comment]
We think issue is solved, reopen it if any problem
