### ISSUE TITLE
Audio problem on bluetooth speakers

### ISSUE THREAD

**Issue by ClarkyKent** [bugsounet/MMM-AssistantMk2#373]
HI i have connected a bluetooth speaker to my raspberry pi 3 and runing MK2 MMM. I have set bluetooth speakers to default audio output. and when i play music or youtube video in chrome, i get sound on speakers. but unable to get it on Mk2 assitant. 

In the configuration steps just after installation of module, when i test audio output and i say NO(N) for step where it asks if i heard google sound, it proposes me available devices/card. and i do not see it there as well. 

FYI i can listen  a wav file via CLI if i type `aplay -D bluealsa test.wav`

In log of MagicMirror i have this error
`ALSA lib pcm.c:8599:(snd_pcm_set_params) Unable to set hw params for PLAYBACK: Device or resource busy`

Thanks in advance!

**Comment by bugsounet** [comment]
hi,
bluetooth and pulseaudio seems making some problem with this module

try to enable this feature: `useHTML5: false,`

**Comment by bugsounet** [comment]
we think this issue is now solved. open it if problem
