### ISSUE TITLE
when i say smatmirror MM stop and come back again 

### ISSUE THREAD

**Issue by haymaan** [bugsounet/MMM-AssistantMk2#374]
i'm trying to get MMM-As* working but no lock.
i've Pi 4 with USB mic and sound come from the Monitor 
last try was 
when i say Smartmirror it's stop MM and than start again (just like pressing Ctrl +Q)

i noobie at that so please is there a How to config the JS file please help 

ive the log file 

0|mm  | [HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }
0|mm  | /home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
0|mm  | npm
0|mm  |  ERR! code ELIFECYCLE
0|mm  | npm ERR! syscall spawn
0|mm  | npm
0|mm  |
0|mm  | ERR!
0|mm  |  file sh
0|mm  | npm ERR! errno ENOENT
0|mm  | npm
0|mm  |  ERR! magicmirror@2.11.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js`
0|mm  | npm ERR! spawn ENOENT
0|mm  | npm ERR!
0|mm  | npm ERR! Failed at the magicmirror@2.11.0 start script.
0|mm  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
0|mm  | npm ERR! A complete log of this run can be found in:
0|mm  | npm ERR!     /home/pi/.npm/_logs/2020-04-26T13_55_32_241Z-debug.log
0|mm  | > magicmirror@2.11.0 start /home/pi/MagicMirror
0|mm  | > DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js
0|mm  | [2020-04-26 15:55:34.351] [LOG]

the error log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.11.0~prestart: magicmirror@2.11.0
6 info lifecycle magicmirror@2.11.0~start: magicmirror@2.11.0
7 verbose lifecycle magicmirror@2.11.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror@2.11.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle magicmirror@2.11.0~start: CWD: /home/pi/MagicMirror
10 silly lifecycle magicmirror@2.11.0~start: Args: [ '-c',
10 silly lifecycle   'DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js' ]
11 info lifecycle magicmirror@2.11.0~start: Failed to exec start script
12 verbose stack Error: magicmirror@2.11.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid magicmirror@2.11.0
14 verbose cwd /home/pi/MagicMirror
15 verbose Linux 4.19.97-v7l+
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v10.20.1
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error magicmirror@2.11.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js`
23 error spawn ENOENT
24 error Failed at the magicmirror@2.11.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

and here is a config 

my config 
{
		module: "MMM-Hotword",
		position: "top_right",
		config: {
		chimeOnFinish: null,
		mic: {
		recordProgram: "arecord",
		device: "plughw:1,0"
		},
		models: [
		{
		hotwords : "smart_mirror",
		file : "smart_mirror.umdl",
		sensitivity : "0.5",
		},
		],
		commands: {
		"smart_mirror": {
		notificationExec: {
		notification: "ASSISTANT_ACTIVATE",
		payload: (detected, afterRecord) => {
		return {profile:"default"}
		}
		},
		restart:false,
		afterRecordLimit:0
		}
		}
		}
		},

        {
            module: "MMM-AssistantMk2",
            position: "fullscreen_above",
            config: {
                ui: "Fullscreen",
                assistantConfig: {
                    latitude: 0000,
                    longitude: ,
                },
                micConfig: {
                    recorder: "arecord",
                    device: "plughw:1,0",
                },
                recipes: [ "with-MMM-Hotword.js" ],
                profiles: {
                    "default": {
                        profileFile: "default.json",
                        lang: "en-US"
                    }
                },
                useA2D: false
            }
        }

**Comment by bugsounet** [comment]
hi, can you retry with:

```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm run rebuild
```

**Comment by haymaan** [comment]
thanks for the reply


the same 


0|mm  | [2020-04-26 16:33:36.243] [ERROR]
0|mm  | SyntaxError: Unexpected end of JSON input
0|mm  |     at JSON.parse (<anonymous>)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-RandomQuranAyah/node_helper.js:64:31
0|mm  |     at /home/pi/MagicMirror/node_modules/async/lib/async.js:726:13
0|mm  |     at /home/pi/MagicMirror/node_modules/async/lib/async.js:52:16
0|mm  |     at done (/home/pi/MagicMirror/node_modules/async/lib/async.js:246:17)
0|mm  |     at /home/pi/MagicMirror/node_modules/async/lib/async.js:44:16
0|mm  |     at /home/pi/MagicMirror/node_modules/async/lib/async.js:723:17
0|mm  |     at /home/pi/MagicMirror/node_modules/async/lib/async.js:167:37
0|mm  |     at Request._callback (/home/pi/MagicMirror/modules/MMM-RandomQuranAyah/node_helper.js:53:11)
0|mm  |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)

**Comment by haymaan** [comment]
when i start the mirror

i get this olso but the mirror works fine 

0|mm       |     at /home/pi/MagicMirror/node_modules/async/lib/async.js:44:16
0|mm       |     at /home/pi/MagicMirror/node_modules/async/lib/async.js:723:17
0|mm       |     at /home/pi/MagicMirror/node_modules/async/lib/async.js:167:37
0|mm       |     at Request._callback (/home/pi/MagicMirror/modules/MMM-RandomQuranAyah/node_helper.js:53:11)
0|mm       |     at Request.self.callback (/home/pi/MagicMirror/node_modules/request/request.js:185:22)
0|mm       | npm ERR! code ELIFECYCLE
0|mm       | npm ERR! errno 1
0|mm       | npm ERR! magicmirror@2.11.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js`
0|mm       | npm ERR! Exit status 1
0|mm       | npm ERR!
0|mm       | npm ERR! Failed at the magicmirror@2.11.0 start script.
0|mm       | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bugsounet** [comment]
Are you sure, this error is related to MMM-AssistantMk2?

**Comment by Sidd-9** [comment]
@bugsounet Sure, I've the same problem, MMM-Hotword works fine but when i had the MMM-AssistantMk2 in the config.js the same error appears, MagicMirror work fine but there is no visual of AssistantMk2. And when I say the hotword, I got the crash.

**Comment by bugsounet** [comment]
I'm not sure ...
because log error says : 

0|mm | at /home/pi/MagicMirror/node_modules/async/lib/async.js:44:16
0|mm | at /home/pi/MagicMirror/node_modules/async/lib/async.js:723:17
0|mm | at /home/pi/MagicMirror/node_modules/async/lib/async.js:167:37
0|mm | at Request._callback (/home/pi/MagicMirror/modules/**MMM-RandomQuranAyah**/node_helper.js:53:11

so... it's not `MMM-AssistantMk2`

**Comment by haymaan** [comment]
okey i've try many things ,know when i say the hotword it's goes to  black and get the google logo but not recording anythink any more after a while it's goes back to MM screen ...


please any more help ,if any one have a working JS can share ....?

**Comment by bugsounet** [comment]
> hi, can you retry with:
> 
> ```shell
> cd ~/MagicMirror/modules/MMM-AssistantMk2
> git pull
> ```
 
and give me result

**Comment by Sidd-9** [comment]
Problem come from grpc. use the grpc@1.23 instead of 1.24

**Comment by bugsounet** [comment]
```sh
~/MagicMirror/modules/MMM-AssistantMk2$ npm list | grep grpc
│ ├── grpc@1.23.4 deduped
├─┬ grpc@1.23.4
```
if you force update libraries ... i will break this dual libraries and break `google-assistant` library

that's why i want the resulat of `git pull` command
if it return an error ... user have force update working pachage

so ... I wait... about this result to solve this

Notes: I don't recommand `grpc@1.24` because this library will crash assistant

**Comment by haymaan** [comment]
> > hi, can you retry with:
> > ```shell
> > cd ~/MagicMirror/modules/MMM-AssistantMk2
> > git pull
> > ```
> 
> and give me result

remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 20 (delta 6), reused 9 (delta 4), pack-reused 0
Unpacking objects: 100% (20/20), done.
From https://github.com/bugsounet/MMM-AssistantMk2
   fde1a86..93224f7  dev        -> origin/dev
Already up to date.
sorry far late reaction

**Comment by haymaan** [comment]
is there any idee how to fix this

0|mm       | /home/pi/MagicMirror/node_modules/electron/dist/electron js/electro                                                n.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_mo                                                dules/grpc/src/node/extension_binary/electron-v6.1-linux-arm-glibc/grpc_node.nod                                                e: undefined symbol: __atomic_store_8

**Comment by bugsounet** [comment]
hi, i need more information before solve it

can you try this:

```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm list | grep grpc
```

the result shoud be : 
```sh
~/MagicMirror/modules/MMM-AssistantMk2$ npm list | grep grpc
│ ├── grpc@1.23.4 deduped
├─┬ grpc@1.23.4
```sh

**Comment by haymaan** [comment]
> hi, i need more information before solve it
> 
> can you try this:
> 
> ```shell
> cd ~/MagicMirror/modules/MMM-AssistantMk2
> npm list | grep grpc
> ```
> 
> the result shoud be :
> 
> ```shell
> ~/MagicMirror/modules/MMM-AssistantMk2$ npm list | grep grpc
> │ ├── grpc@1.23.4 deduped
> ├─┬ grpc@1.23.4
> ```sh
> ```


here you go 




| +-- grpc@1.24.2 deduped
+-- grpc@1.24.2

**Comment by haymaan** [comment]
ive update to the AssistantMk and now it's olny black screeen ,the update when well no errors and check the mic and the spreakers


0|mm  | [2020-05-01 14:27:24.050] [ERROR]  Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm  | Expected directory: electron-v6.1-linux-arm-glibc
0|mm  | Found: [node-v64-linux-arm-glibc]
0|mm  | This problem can often be fixed by running "npm rebuild" on the current system
0|mm  | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-arm-glibc/grpc_node.node'
0|mm  | Require stack:
0|mm  | - /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js
0|mm  | - /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js
0|mm  | - /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js
0|mm  | - /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/index.js
0|mm  | - /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/assistant.js
0|mm  | - /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js
0|mm  | - /home/pi/MagicMirror/modules/MMM-AssistantMk2/components/assistant.js
0|mm  | - /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js
0|mm  | - /home/pi/MagicMirror/js/app.js
0|mm  | - /home/pi/MagicMirror/js/electron.js
0|mm  | - /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
0|mm  | -
0|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:786:30)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
0|mm  |     at Module.load (internal/modules/cjs/loader.js:645:32)
0|mm  |     at Function.Module._load (internal/modules/cjs/loader.js:560:12)
0|mm  |     at Module.require (internal/modules/cjs/loader.js:685:19)
0|mm  |     at require (internal/modules/cjs/helpers.js:16:16)
0|mm  |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12)
0|mm  |     at Module._compile (internal/modules/cjs/loader.js:786:30)
0|mm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10) {
0|mm  |   code: 'MODULE_NOT_FOUND'
0|mm  | }
0|mm  | [2020-05-01 14:27:24.403] [LOG]
0|mm  | Launching application.

**Comment by bugsounet** [comment]
ok, this is my diag:

you have forced to install grpc@1.24.2
** surely with npm install grpc **
but it's this version is not compatible with RPI pi

that why i have forced in package.json and locked to 1.23.4

so now to solve this follow this step:

```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
rm -rf package.json package-lock.json node_modules
git checkout package.json
git pull
rpm run rebuild
````

now do a proper install and execute automatic installation

**Comment by haymaan** [comment]
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ git pull
Updating eeecb9e..0e659b1
error: Your local changes to the following files would be overwritten by merge:
        MMM-AssistantMk2.js
Please commit your changes or stash them before you merge.
Aborting

**Comment by bugsounet** [comment]
oupss sorry `npm run rebuild` for the last part

**Comment by haymaan** [comment]
know the MM start but still nothing from MK2....and its give me again that MK2 needs update 


i thing the hotword is working but the mk2 not 

0|mm  | [2020-05-01 18:19:43.317] [LOG]    [HOTWORD] Detector starts listening.
0|mm  | [2020-05-01 18:19:43.957] [LOG]
0|mm  | [AMK2] MMM-AssistantMk2 Version: 3.2.2
0|mm  | [2020-05-01 18:19:44.029] [LOG]
0|mm  | [AMK2] AssistantMk2 is initialized.
0|mm  | [2020-05-01 18:19:44.057] [LOG]
0|mm  | /nodehelper/get arabic with statuscode-200
0|mm  | [2020-05-01 18:19:44.078] [LOG]
0|mm  | /nodehelper/get translation with statuscode-200
0|mm  | [2020-05-01 18:19:44.084] [LOG]
0|mm  | /nodehelper/result-Al-Mumtahana:12
0|mm  | [2020-05-01 18:19:52.130] [LOG]    [HOTWORD] Detected: smart_mirror
0|mm  | [2020-05-01 18:19:52.134] [LOG]
0|mm  | [HOTWORD] stops.
0|mm  | [2020-05-01 18:19:52.149] [LOG]
0|mm  | [HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file:                                         null }
0|mm  | [2020-05-01 18:20:23.337] [LOG]
0|mm  | [HOTWORD] begins.
0|mm  | [2020-05-01 18:20:23.341] [LOG]
0|mm  | [HOTWORD] Detector starts listening.

**Comment by haymaan** [comment]
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ npm list | grep grpc
| +-- grpc@1.23.4 deduped
+-- grpc@1.23.4

**Comment by bugsounet** [comment]
perfect, now let's configure MMM-Hotword by reading [wiki](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Configuration-Sample#use-with-mmm-hotword)

**Comment by bugsounet** [comment]
notes: if want to use another recoder like MMM-Hotword (if it's so complex for you)
don't forget to delete MMM-Hotword or disable it in your configuration file

**Comment by haymaan** [comment]
ive stop the  MMM-HOTWORD and know the mm starts but nothing happend it dosnt even act to hot word or any thing..
can you please check the config please







        {
            module: "MMM-AssistantMk2",
            position: "fullscreen_above",
            config: {
                ui: "Fullscreen",
                assistantConfig: {
                    latitude: xxxxxxxx,
                    longitude: xxxxxxxx,
                },
                micConfig: {
                    recorder: "arecord",
                    device: "plughw:1,0",
                },
                recipes: [ "with-MMM-Hotword.js" ],
                profiles: {
                    "default": {
                        profileFile: "default.json",
                        lang: "en-US"
                    }
                },
                useA2D: false

**Comment by bugsounet** [comment]
humm ...

```js
    {
        module: "MMM-AssistantMk2",
        position: "fullscreen_above",
        config: {
            ui: "Fullscreen",
            assistantConfig: {
                latitude: xxxxxxxx,
                longitude: xxxxxxxx,
            },
            micConfig: {
                recorder: "arecord",
                device: "plughw:1,0",
            },
            recipes: [ "with-MMM-Hotword.js" ],
            profiles: {
                "default": {
                    profileFile: "default.json",
                    lang: "en-US"
                }
            },
            useA2D: false
        }
    },
```
missing 2 brakets

**Comment by haymaan** [comment]
They are already in I hadn't copy them ,the mm start but the mk2 not working the rest of the modules works

**Comment by bugsounet** [comment]
I say : 

> perfect, now let's configure MMM-Hotword by reading [wiki](https://github.com/bugsounet/MMM-AssistantMk2/wiki/Configuration-Sample#use-with-mmm-hotword)


> notes: if want to use another recoder like MMM-Hotword (if it's so complex for you)
> don't forget to delete MMM-Hotword or disable it in your configuration file

because... Your MMM-Hotword configuration is not correct

**Comment by bugsounet** [comment]
4 days ago ... i say:

> and for `MMM-Hotword` ... when you says it's work... I just `Yes, it reconize the keyword`
> and i will **NEVER** send a notification to MMM-AssistantMk2

**Comment by haymaan** [comment]
Yes ive installed mmmhot separate and put it separately in the mm config know I've deleted the hotword config and I'll check where to implant it with mk2 ...if I copy the basic config it's not working eather ,,will you please send me he correct config ??

**Comment by haymaan** [comment]
I'll read it carefully and try it and will till you the results

**Comment by bugsounet** [comment]
so : 

wiki says:

 1) snowboy library

if sure do try:
```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm run update
```
execute automatic installtion.
Do all normal process , it will ask you to install snowboy library (respond Y) and execute electron rebuild (respond Y)

2) configure snowboy in AMk2
in config.js:

```sh
    {
        module: "MMM-AssistantMk2",
        position: "fullscreen_above",
        config: {
            ui: "Fullscreen",
            assistantConfig: {
                latitude: xxxxxxxx,
                longitude: xxxxxxxx,
            },
            micConfig: {
                recorder: "arecord",
                device: "plughw:1,0",
            },
            recipes: [ "with-MMM-Hotword.js" ],
            profiles: {
                "default": {
                    profileFile: "default.json",
                    lang: "en-US"
                }
            },
            useA2D: false,
            useSnowboy: true,
            snowboy: {
                  Frontend: false,
                  Model: "smart_mirror"
            },
        }
    },
```
2.1) delete MMM-Hotword of your config.js file
2.2) save your file
3) restart MM
4) try now call assistant with `smart mirror`

**Comment by haymaan** [comment]
Thanks I'll try it and report back

**Comment by haymaan** [comment]
hello,


this is my config mm


{
            module: "MMM-AssistantMk2",
            position: "fullscreen_above",
            config: {
                ui: "Fullscreen",
                assistantConfig: {
                    latitude:  5.566310,
                    longitude: 51.957729,
                },
                micConfig: {
                    recorder: "arecord",
                    device: "plughw:1,0",
                },
                recipes: ["with-MMM-Hotword.js"],
                profiles: {
                    "default": {
                        profileFile: "default.json",
                        lang: "en-US"
                    }
                },
                useA2D: false,
                useSnowboy: true,
                snowboy: {
                    Frontend: false,
                    Model: "smart_mirror"
                }
            }
        }
    ]
};




i remove the Hotword from JS and save the file and pm2 restart mm ,the mm works but still nothing happend ,do i need to modifie other files in MK2 olso ???


olso when i see the logs i found this

0|mm       | SyntaxError: Unexpected token ]
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:722:23)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:645:32)
0|mm       |     at Function.Module._load (internal/modules/cjs/loader.js:560:12)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:685:19)
0|mm       |     at require (internal/modules/cjs/helpers.js:16:16)
0|mm       |     at loadConfig (/home/pi/MagicMirror/js/app.js:69:12)
0|mm       |     at App.start (/home/pi/MagicMirror/js/app.js:210:3)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:115:7)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:786:30)

**Comment by bugsounet** [comment]
wow ! sorry .. I can't learning you how delete and do a copy past...

**Comment by haymaan** [comment]
I'll check it again and report back thanks

**Comment by haymaan** [comment]
thank you at last it's work it's was a probleem with config the MK2 thanks again,,,
one small thing if i want to change the voice of google i want a male do ou know how ?
thanks
