### ISSUE TITLE
Completed installation and used the sample configuration but doesn't word when running MM

### ISSUE THREAD

**Issue by lolkaese1** [bugsounet/MMM-AssistantMk2#375]
Im using a RP4B. I installed the Mk2 and successfully checked my mic and the test conversation with Google assistant. Then I Copied the Simple Configuration into my config.js but when running the Mirror, the Google assistant doesn't show up, after saying "Okay Google". I just installed the basic version without any recipes. I also tried "npm rebuild" and "npm run rebuild". My node ist on v12.x 

Does anyone had a simular issue like this ? 
Is there a way to test the Microphone again after the installation is completed ?

**Comment by lolkaese1** [comment]
I think its something with my audit.
After "npm audit"

> 

Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ google-assistant                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ google-assistant > grpc > node-pre-gyp > mkdirp > minimist   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grpc                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ grpc > node-pre-gyp > mkdirp > minimist                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ google-assistant                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ google-assistant > grpc > node-pre-gyp > tar > mkdirp >      │
│               │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grpc                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ grpc > node-pre-gyp > tar > mkdirp > minimist                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ google-assistant                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ google-assistant > grpc > node-pre-gyp > rc > minimist       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.2.1 <1.0.0 || >=1.2.3                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ grpc                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ grpc > node-pre-gyp > rc > minimist                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1179                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 6 low severity vulnerabilities in 758 scanned packages
  6 vulnerabilities require manual review. See the full report for details.

> 

How can i fix these ?

**Comment by bugsounet** [comment]
> Im using a RP4B. I installed the Mk2 and successfully checked my mic and the test conversation with Google assistant. Then I Copied the Simple Configuration into my config.js but when running the Mirror, the Google assistant doesn't show up, after saying "Okay Google". I just installed the basic version without any recipes. I also tried "npm rebuild" and "npm run rebuild". My node ist on v12.x

Hi, `MMM-AssistantMk2` need an keyword Activator for working
Read wiki for install it
I remind you, however, that this is an `SDK project`.


> found 6 low severity vulnerabilities in 758 scanned packages
> 6 vulnerabilities require manual review. See the full report for details.
> How can i fix these ?

Try to updating package
I will not give any help above because you could break the compilation of this module

**Comment by bugsounet** [comment]
we think the problem is now solved
