### ISSUE TITLE
MM isn´t starting anymore after installation

### ISSUE THREAD

**Issue by renzo79** [bugsounet/MMM-AssistantMk2#377]
Hello,

I´ve made a fresh installation after an installation a new Micro-SD-Card.

And I´ve no idea what is wrong, but after the Installation of MK2 the whole mirror isn´t starting anymore!?

Can somebody give me a bit support
Thanks thousand times

[2020-04-30 07:50:14.277] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v6.0-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v6.0-linux-arm-glibc/grpc_node.node'
Require stack:
- /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js
- /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js
- /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js
- /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/index.js
- /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/assistant.js
- /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js
- /home/pi/MagicMirror/modules/MMM-AssistantMk2/components/assistant.js
- /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js

**Comment by bugsounet** [comment]
hi, i need more information before solve it

can you try this:

```sh
cd ~/MgaicMirror/modules/MMM-AssistantMk2
npm list | grep grpc
```

the result shoud be : 
```sh
~/MagicMirror/modules/MMM-AssistantMk2$ npm list | grep grpc
│ ├── grpc@1.23.4 deduped
├─┬ grpc@1.23.4
```sh

**Comment by renzo79** [comment]
Thank you very much!!!!

pi@MagicMirror:~ $ cd MagicMirror/modules/MMM-AssistantMk2/
pi@MagicMirror:~/MagicMirror/modules/MMM-AssistantMk2 $ npm list | grep grpc
│ ├── grpc@1.24.2 deduped
├─┬ grpc@1.24.2
pi@MagicMirror:~/MagicMirror/modules/MMM-AssistantMk2 $

**Comment by bugsounet** [comment]
hummm ok...

```sh
cd MagicMirror/modules/MMM-AssistantMk2/
npm list | grep google-assistant
cat package.json | grep google-assistant
cat package.json | grep grpc
```

give me result and i give you explain and solve command

**Comment by renzo79** [comment]
pi@MagicMirror:~ $ cd MagicMirror/modules/MMM-AssistantMk2/
pi@MagicMirror:~/MagicMirror/modules/MMM-AssistantMk2 $ npm list | grep google-assistant
├─┬ google-assistant@0.5.4
pi@MagicMirror:~/MagicMirror/modules/MMM-AssistantMk2 $ cat package.json | grep google-assistant
    "google-assistant": "^0.5.4",
pi@MagicMirror:~/MagicMirror/modules/MMM-AssistantMk2 $ cat package.json | grep grpc
    "grpc": "^1.24.2",
pi@MagicMirror:~/MagicMirror/modules/MMM-AssistantMk2 $ ^C
pi@MagicMirror:~/MagicMirror/modules/MMM-AssistantMk2 $

**Comment by renzo79** [comment]
Thanks for your help!!!

**Comment by bugsounet** [comment]
ok, this is my diag:

you have forced to install grpc@1.24.2
** surely with npm install grpc **
but it's this version is not compatible with RPI pi

that why i have forced in package.json and locked to 1.23.4

so now to solve this follow this step:

```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
rm -rf package.json package-lock.json node_modules
git checkout package.json
git pull
rpm run rebuild
```
now do a proper install and execute automatic installation

**Comment by bugsounet** [comment]
Hi, we think the problem is now solved
