### ISSUE TITLE
MM wont start after Install

### ISSUE THREAD

**Issue by baudi94** [bugsounet/MMM-AssistantMk2#381]
So I did everything according to your guide but when I start my MM with npm start I get the following

`at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10) {
  code: 'MODULE_NOT_FOUND'`

I checked the grep version and everything from the unsolved Issues but everything is the version you recommended.

Cheers

**Comment by bugsounet** [comment]
Hi,

gprc library seems not installed correctly

try this command:

```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm run rebuild
```

**Comment by anhdao2871989** [comment]
Hi 

I'm trying to load google assistance to my mirror everything seem working fine except google assistance did not come up . when i run  
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm run rebuild

code come back error rebuild failed .Would you help me troubleshoot this issue .Thank you 

Rebuild failed
 [@bugsounet/snowboy] Do you want to execute electron rebuild ? [Y/n]
Your choice: y
- Searching dependency tree
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
make: Entering directory '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/@bugsounet/snowboy/build'
  CXX(target) Release/obj.target/snowboy/lib/snowboy.o
In file included from /home/pi/.electron-gyp/6.1.10/include/node/v8-internal.h:14,
                 from /home/pi/.electron-gyp/6.1.10/include/node/v8.h:25,
                 from /home/pi/.electron-gyp/6.1.10/include/node/node.h:63,
                 from ../../../nan/nan.h:56,
                 from ../lib/snowboy.cc:1:
/home/pi/.electron-gyp/6.1.10/include/node/v8config.h:326:49: warning: ‘MicrotasksCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/pi/.electron-gyp/6.1.10/include/node/v8.h:8205:3: note: in expansion of macro ‘V8_DEPRECATE_SOON’
   V8_DEPRECATE_SOON("Use *WithData version.",
   ^~~~~~~~~~~~~~~~~
/home/pi/.electron-gyp/6.1.10/include/node/v8config.h:326:49: warning: ‘MicrotasksCompletedCallback’ is deprecated [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))

**Comment by bugsounet** [comment]
humm..

can you give me the vesion of `gcc` compilateur used ?

```
gcc -v
```

**Comment by anhdao2871989** [comment]
Sure . here is it 

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/7/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 7.3.0-19' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 7.3.0 (Raspbian 7.3.0-19)

**Comment by bugsounet** [comment]
humm, i see the problem

but i can't help you ;(

you used Raspbian 7, but I have build this program for Raspbian 8 ...
I can't downgrade my rpi actually for more fixe, sorry

sorry, unfortunately the solution is to install raspbian 8 (buster)

**Comment by anhdao2871989** [comment]
i will re-image my pi from 7 to 8 .thank for the help

**Comment by anhdao2871989** [comment]
how do you upgrade GCC  from 7 to 8

**Comment by bugsounet** [comment]
solved with last update (missing library)
