### ISSUE TITLE
MMM-Assistant is not listening. 

### ISSUE THREAD

**Issue by kevin07696** [bugsounet/MMM-AssistantMk2#383]
**Describe the problem**
The assistant is not waking or making any responses

**To Reproduce**
I followed the steps for the auto installation and used the full detailed configuration from the configuration sample tab in the wiki

**Expected behavior**
Some sort of response in the backend console such as "listening" or a beep to signify that the assistant is awake.

**backend log**
pi@cmm:~/MagicMirror $ npm start dev

> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-05-05 12:25:49.091] [LOG]    Starting MagicMirror: v2.11.0
[2020-05-05 12:25:49.138] [LOG]    Loading config ...
[2020-05-05 12:25:49.156] [LOG]    Loading module helpers ...
[2020-05-05 12:25:49.162] [LOG]    No helper found for module: alert.
[2020-05-05 12:25:49.165] [LOG]    No helper found for module: clock.
[2020-05-05 12:25:54.662] [LOG]    Initializing new module helper ...
[2020-05-05 12:25:54.664] [LOG]    Module helper loaded: MMM-AssistantMk2
[2020-05-05 12:25:54.666] [LOG]    All module helpers loaded.
[2020-05-05 12:25:55.148] [LOG]    Starting server on port 8080 ... 
[2020-05-05 12:25:55.196] [LOG]    Server started ...
[2020-05-05 12:25:55.198] [LOG]    Connecting socket for: MMM-AssistantMk2
[2020-05-05 12:25:55.201] [LOG]    Sockets connected & modules started ...
[2020-05-05 12:25:55.632] [LOG]    Launching application.
[2020-05-05 12:26:06.326] [LOG]    [AMK2] MMM-AssistantMk2 Version: 3.2.3
[2020-05-05 12:26:06.331] [LOG]    [AMK2] Use HTML5 for audio response
[2020-05-05 12:26:06.352] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-TelegramBot.js
[2020-05-05 12:26:06.361] [LOG]    [AMK2] ASSISTANT_WEB Started
[2020-05-05 12:26:06.365] [LOG]    [AMK2] AssistantMk2 is initialized.

**frontend log**
Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/en.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/default/alert//alert.js
module.js:479 Module registered: alert
loader.js:150 Bootstrapping module: alert
loader.js:179 Load script: modules/default/alert/classie.js
loader.js:179 Load script: modules/default/alert/modernizr.custom.js
loader.js:179 Load script: modules/default/alert/notificationFx.js
loader.js:155 Scripts loaded for: alert
loader.js:194 Load stylesheet: modules/default/alert/ns-default.css
loader.js:194 Load stylesheet: vendor/css/font-awesome.css
loader.js:157 Styles loaded for: alert
translator.js:175 alert - Load translation fallback: translations/en.json
/home/pi/MagicMirror…rity-warnings.js:95 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
  protocols.This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/default/alert//alert.js
- http://localhost:8080/modules/default/alert/classie.js
- http://localhost:8080/modules/default/alert/modernizr.custom.js
- http://localhost:8080/modules/default/alert/notificationFx.js
- http://localhost:8080/modules/default/alert/ns-default.css
- http://localhost:8080/vendor/css/font-awesome.css
- http://localhost:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/all.min.css
- http://localhost:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/v4-shims.min.css
  
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
/home/pi/MagicMirror…ity-warnings.js:145 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
loader.js:159 Translations loaded for: alert
loader.js:179 Load script: modules/default/clock//clock.js
module.js:479 Module registered: clock
loader.js:150 Bootstrapping module: clock
loader.js:179 Load script: vendor/node_modules/moment/min/moment-with-locales.js
loader.js:179 Load script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
loader.js:179 Load script: vendor/node_modules/suncalc/suncalc.js
loader.js:155 Scripts loaded for: clock
loader.js:194 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:157 Styles loaded for: clock
loader.js:159 Translations loaded for: clock
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:479 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: /modules/MMM-AssistantMk2/components/response.js
loader.js:179 Load script: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
translator.js:175 MMM-AssistantMk2 - Load translation fallback: translations/en.json
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: css/custom.css
(index):1 Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:203 Error on loading stylesheet: css/custom.css
alert.js:153 Starting module: alert
clock.js:45 Starting module: clock
main.js:474 All modules started!
﻿
**config.js**

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	timeFormat: 12,
	units: "imperial",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "alert",
		},
		// {
		// 	module: "updatenotification",
		// 	position: "top_bar"
		// },
		{
			module: "clock",
			position: "top_left"
		},
		// {
		// 	module: "calendar",
		// 	header: "US Holidays",
		// 	position: "top_left",
		// 	config: {
		// 		calendars: [
		// 			{
		// 				symbol: "calendar-check",
		// 				url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
		// 		]
		// 	}
		// },
		// {
		// 	module: "compliments",
		// 	position: "lower_third"
		// },
		// {
		// 	module: "currentweather",
		// 	position: "top_right",
		// 	config: {
		// 		location: "New York",
		// 		locationID: "", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
		// 		appid: "YOUR_OPENWEATHER_API_KEY"
		// 	}
		// },
		// {
		// 	module: "weatherforecast",
		// 	position: "top_right",
		// 	header: "Weather Forecast",
		// 	config: {
		// 		location: "New York",
		// 		locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
		// 		appid: "YOUR_OPENWEATHER_API_KEY"
		// 	}
		// },
		// {
		// 	module: "newsfeed",
		// 	position: "bottom_bar",
		// 	config: {
		// 		feeds: [
		// 			{
		// 				title: "New York Times",
		// 				url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
		// 			}
		// 		],
		// 		showSourceTitle: true,
		// 		showPublishDate: true,
		// 		broadcastNewsFeeds: true,
		// 		broadcastNewsUpdates: true
		// 	}
		// },
		{
			module: "MMM-AssistantMk2",
			position: "fullscreen_above",
			config: {
				debug: false,
				ui: "Fullscreen", // Classic2, Classic or Simple
				// if you want Google Nest ui style
				// set Fullscreen ui AND fullscreen_above position
				assistantConfig: {
					projectId: "", // Required to use gaction.
					modelId: "", // (OPTIONAL for gaction)
					instanceId: "", // (OPTIONAL for gaction)
					latitude: 51.508530,
					longitude: -0.076132,
				},
				responseConfig: {
					useHTML5: true, // sound render by HTML5
					useScreenOutput: true,
					useAudioOutput: true,
					useChime: true,
					timer: 5000,
					myMagicWord: false,
					//Your prefer sound play program.
					//By example, if you are running this on OSX, `afplay` could be available.
					//by default mpg321 play program is enabled
					//if audio output cutting try with mpg123 or cvlc program
					playProgram: "mpg321",
					chime: {
						beep: "beep.mp3",
						error: "error.mp3",
						continue: "continue.mp3",
						open: "Google_beep_open.mp3",
						close: "Google_beep_close.mp3",
					},
					// false - animated icons, 'standby' - static icons only for standby state, true - all static icons
					useStaticIcons: false
				},
				micConfig: { // put there configuration generated by auto-installer
					recorder: "arecord",
					device: "plughw:1",
				},
				customActionConfig: {
				autoMakeAction: false,
				autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
				actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
				},
				recipes: [ "with-MMM-TelegramBot.js" ],
				profiles: {
					"default": {
						profileFile: "default.json",
						lang: "en-US"
					}
				},
				useA2D: false,
				A2DStopCommand: "stop",
				useSnowboy: false,
				snowboy: {
					audioGain: 2.0,
					Frontend: true,
					Model: "jarvis",
					Sensitivity: null
				},
			},
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Environment:**
 - Device : [RPI 2b, Respeaker 4 mic array]
 - OS: [Raspbian Stretch]
 - Node Version : v12.16.3
 - Etc.

**Comment by bugsounet** [comment]
> I followed the steps for the auto installation and used the full detailed configuration from the configuration sample tab in the wiki

Hi,
Just one step missing...
Read Wiki

**Comment by kevin07696** [comment]
Oh I forgot is it the Google Assistant setup? I set that up too. I just don't get the notification tab that allows for the assistant to wake up. Do I add MMM_Hotword/MMM_Snowboy or do I npm install snowboy? Is that last step? Sorry, I did read the wiki I'm confused on how to use it.

**Comment by kevin07696** [comment]
I got the MMM-Assistant to listen. Thanks for making this module.
