### ISSUE TITLE
Installing on lubuntu

### ISSUE THREAD

**Issue by jimenezfuentesd** [bugsounet/MMM-AssistantMk2#384]
Hi! im trying to install MagicMirror and Google Assistant on an old laptop Dell Latitude x300... i have successfully installed MM and Assistantmk2 or at least is what i think...
when i run MM npm start the app starts and the google assistant icon appears where it is supposed to but when i say something to the mic i get no response, also on terminal i get  code: 'MODULE_NOT_FOUND'
im trying to use the integrated snowboy via useSnowboy:true...
i dont know where or how i have to configure my speaker and mic so any help would be great because it has been a really pain getting it to work in linux because all the guides i have found in internet are intended for Raspberry Pi

this is my config.js

modules: [

{
  module: "MMM-AssistantMk2",
  position: "fullscreen_above",
  config: {
    debug: false,
    ui: "Classic2", // Classic2, Classic or Simple
    // if you want Google Nest ui style
    // set Fullscreen ui AND fullscreen_above position
    assistantConfig: {
      projectId: "", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: 51.508530,
      longitude: -0.076132,
    },

    responseConfig: {
      useHTML5: true, // sound render by HTML5
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: false,
      //Your prefer sound play program.
      //By example, if you are running this on OSX, `afplay` could be available.
      //by default mpg321 play program is enabled
      //if audio output cutting try with mpg123 or cvlc program
      playProgram: "mpg321",
      chime: {
        beep: "beep.mp3",
        error: "error.mp3",
        continue: "continue.mp3",
        open: "Google_beep_open.mp3",
        close: "Google_beep_close.mp3",
      },
      // false - animated icons, 'standby' - static icons only for standby state, true - all static icons
      useStaticIcons: false
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1",
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    useA2D: false,
    A2DStopCommand: "stop",
    useSnowboy: true,
    snowboy: {
      audioGain: 2.0,
      Frontend: true,
      Model: "jarvis",
      Sensitivity: null
    },
  },
},

**Comment by jimenezfuentesd** [comment]
this is what i get when running with clock and GA only...


Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/es.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:479 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: /modules/MMM-AssistantMk2/components/response.js
loader.js:179 Load script: /modules/MMM-AssistantMk2/ui/Classic2/Classic2.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: /modules/MMM-AssistantMk2/ui/Classic2/Classic2.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
translator.js:175 MMM-AssistantMk2 - Load translation fallback: translations/en.json
/home/diego/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
  protocols.This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/es.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/MMM-AssistantMk2//MMM-AssistantMk2.js
- http://localhost:8080/modules/MMM-AssistantMk2/components/response.js
- http://localhost:8080/modules/MMM-AssistantMk2/ui/Classic2/Classic2.js
- http://localhost:8080/modules/MMM-AssistantMk2/ui/Classic2/Classic2.css
  
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/diego/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95
/home/diego/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
(anonymous) @ /home/diego/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:179 Load script: modules/default/alert//alert.js
module.js:479 Module registered: alert
loader.js:150 Bootstrapping module: alert
loader.js:179 Load script: modules/default/alert/classie.js
loader.js:179 Load script: modules/default/alert/modernizr.custom.js
loader.js:179 Load script: modules/default/alert/notificationFx.js
loader.js:155 Scripts loaded for: alert
loader.js:194 Load stylesheet: modules/default/alert/ns-default.css
loader.js:194 Load stylesheet: vendor/css/font-awesome.css
loader.js:157 Styles loaded for: alert
translator.js:175 alert - Load translation fallback: translations/en.json
loader.js:159 Translations loaded for: alert
loader.js:179 Load script: modules/default/updatenotification//updatenotification.js
module.js:479 Module registered: updatenotification
loader.js:150 Bootstrapping module: updatenotification
loader.js:155 Scripts loaded for: updatenotification
loader.js:157 Styles loaded for: updatenotification
loader.js:159 Translations loaded for: updatenotification
loader.js:179 Load script: modules/default/clock//clock.js
module.js:479 Module registered: clock
loader.js:150 Bootstrapping module: clock
loader.js:179 Load script: vendor/node_modules/moment/min/moment-with-locales.js
loader.js:179 Load script: vendor/node_modules/moment-timezone/builds/moment-timezone-with-data.js
loader.js:179 Load script: vendor/node_modules/suncalc/suncalc.js
loader.js:155 Scripts loaded for: clock
loader.js:194 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:157 Styles loaded for: clock
loader.js:159 Translations loaded for: clock
loader.js:194 Load stylesheet: css/custom.css
(index):1 Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:203 Error on loading stylesheet: css/custom.css
stylesheet.onerror @ loader.js:203
error (async)
loadFile @ loader.js:202
loadNextModule @ loader.js:38
(anonymous) @ loader.js:31
(anonymous) @ loader.js:125
(anonymous) @ loader.js:161
loadTranslations @ module.js:334
(anonymous) @ loader.js:158
loadNextDependency @ module.js:299
(anonymous) @ module.js:296
stylesheet.onload @ loader.js:200
load (async)
loadFile @ loader.js:199
loadFile @ loader.js:257
loadNextDependency @ module.js:294
loadDependencies @ module.js:303
loadStyles @ module.js:269
(anonymous) @ loader.js:156
loadNextDependency @ module.js:299
(anonymous) @ module.js:296
script.onload @ loader.js:184
alert.js:153 Starting module: alert
updatenotification.js:14 Start updatenotification
clock.js:45 Starting module: clock
main.js:474 All modules started!

**Comment by jimenezfuentesd** [comment]
![15887160555385405787358832538791](https://user-images.githubusercontent.com/64869510/81120358-8b676a00-8efa-11ea-8fd3-a3cac710a94d.jpg)
As you can see the assistant icon is present

**Comment by jimenezfuentesd** [comment]
and this is backend log

`
> magicmirror@2.11.0 start /home/diego/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-05-05 19:01:30.617] [LOG]    Starting MagicMirror: v2.11.0
[2020-05-05 19:01:30.626] [LOG]    Loading config ...
[2020-05-05 19:01:30.630] [LOG]    Loading module helpers ...
[2020-05-05 19:01:32.095] [LOG]    Initializing new module helper ...
[2020-05-05 19:01:32.096] [LOG]    Module helper loaded: MMM-AssistantMk2
[2020-05-05 19:01:32.097] [LOG]    No helper found for module: alert.
[2020-05-05 19:01:32.150] [LOG]    Initializing new module helper ...
[2020-05-05 19:01:32.151] [LOG]    Module helper loaded: updatenotification
[2020-05-05 19:01:32.152] [LOG]    No helper found for module: clock.
[2020-05-05 19:01:32.152] [LOG]    All module helpers loaded.
[2020-05-05 19:01:32.313] [LOG]    Starting server on port 8080 ... 
[2020-05-05 19:01:32.353] [LOG]    Server started ...
[2020-05-05 19:01:32.354] [LOG]    Connecting socket for: MMM-AssistantMk2
[2020-05-05 19:01:32.355] [LOG]    Connecting socket for: updatenotification
[2020-05-05 19:01:32.355] [LOG]    Sockets connected & modules started ...
[2020-05-05 19:01:32.501] [LOG]    Launching application.
[2020-05-05 19:01:37.407] [LOG]    [AMK2] MMM-AssistantMk2 Version: 3.2.3
[2020-05-05 19:01:37.410] [LOG]    [AMK2] Use HTML5 for audio response
[2020-05-05 19:01:37.425] [LOG]    Whoops! There was an uncaught exception...
[2020-05-05 19:01:37.436] [ERROR]  Error: Cannot find module '@bugsounet/snowboy'
Require stack:
- /home/diego/MagicMirror/modules/MMM-AssistantMk2/node_helper.js
- /home/diego/MagicMirror/js/app.js
- /home/diego/MagicMirror/js/electron.js
- /home/diego/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/diego/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/diego/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Class.initialize (/home/diego/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:136:20)
    at Class.socketNotificationReceived (/home/diego/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:33:14)
    at Socket.<anonymous> (/home/diego/MagicMirror/js/node_helper.js:113:11)
    at Socket.emit (events.js:200:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/diego/MagicMirror/modules/MMM-AssistantMk2/node_helper.js',
    '/home/diego/MagicMirror/js/app.js',
    '/home/diego/MagicMirror/js/electron.js',
    '/home/diego/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[2020-05-05 19:01:37.479] [LOG]    MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-05-05 19:01:37.480] [LOG]    If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
`

**Comment by jimenezfuentesd** [comment]
I have noticed that /@bugsounet/snowboy dir is missing from /MagicMirror/modules/MMM-AssistantMk2/nodes_modules

Doesn't it supposed to be created when installing MMM-assistantMk2?

**Comment by bugsounet** [comment]
Hi,
I think you don't installl this library snowboy
retry npm install and respond `Y` to this:

```sh
Snowboy detector embed version
If you want to use it, remove your other detector !
like: MMM-HotWord or MMM-Snowboy
Do you want to use it ? [Y/n] 
```

**Comment by jimenezfuentesd** [comment]
Thanks for the reply... 

When I run npm install it doesn't ask for nothing, it just runs and finish with "0 vulnerabilities"

I will post the result of 'npm install' as soon as I get MM working again because I did a fresh install of everything including linux and now I'm stuck at black screen with mouse pointer...

**Comment by jimenezfuentesd** [comment]
Ok, I have a backup of the entire MM folder and I noticed that it has MMM-Hotword installed from a previous test. So when I run npm install on MMM-AssistantMk2 folder it assumes that I'll be using hotword because it is present...

Again, as soon as I have MM running again i will try npm install Assistant and post the result...

Thank you very much!

**Comment by jimenezfuentesd** [comment]
i got MM running again. i had an issue with vendor and fonts folders...
this is what i get when run npm install on MMM-AssistantMk2 folder after removing all folders but default in /MagicMirror/modules


root@ubuntu:/home/diego/MagicMirror/modules/MMM-AssistantMk2# npm install
npm WARN lifecycle MMM-AssistantMk2@3.2.3~postinstall: cannot run in wd MMM-AssistantMk2@3.2.3 installer/postinstall.sh (wd=/home/diego/MagicMirror/modules/MMM-AssistantMk2)
audited 758 packages in 10.248s

2 packages are looking for funding
  run `npm fund` for details

found 6 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
root@ubuntu:/home/diego/MagicMirror/modules/MMM-AssistantMk2#

**Comment by bugsounet** [comment]
> root@ubuntu:/home/diego/MagicMirror/modules/MMM-AssistantMk2#

?

**Comment by bugsounet** [comment]
MM doc says : **NOT INSTALL MM WITH ROOT**

**Comment by jimenezfuentesd** [comment]
if i dont use root it returns an error...

npm WARN checkPermissions Missing write access to /home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules/tslib
npm WARN checkPermissions Missing write access to /home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules/electron-rebuild
npm WARN checkPermissions Missing write access to /home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules/tslib
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules/tslib'
npm ERR!  { Error: EACCES: permission denied, access '/home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules/tslib'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules/tslib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules/tslib' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/diego/.npm/_logs/2020-05-06T15_31_56_345Z-debug.log

**Comment by jimenezfuentesd** [comment]
this is with sudo.


diego@ubuntu:~/MagicMirror/modules/MMM-AssistantMk2$ sudo npm install
[sudo] password for diego: 
npm WARN lifecycle MMM-AssistantMk2@3.2.3~postinstall: cannot run in wd MMM-AssistantMk2@3.2.3 installer/postinstall.sh (wd=/home/diego/MagicMirror/modules/MMM-AssistantMk2)
audited 758 packages in 7.01s

2 packages are looking for funding
  run `npm fund` for details

found 6 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by jimenezfuentesd** [comment]
Should i change the moldule folder ownership?

**Comment by bugsounet** [comment]
> npm ERR! Error: EACCES: permission denied, access '/home/diego/MagicMirror/modules/MMM-AssistantMk2/node_modules/tslib'

I say ...
> `MM` doc says : NOT INSTALL `MM` WITH ROOT

`MM` means ... **M**agic**Mirror**

**Comment by jimenezfuentesd** [comment]
trying to install MM with no root

diego@ubuntu:~/MagicMirror$ npm install
npm WARN checkPermissions Missing write access to /home/diego/MagicMirror/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/diego/MagicMirror/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/diego/MagicMirror/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/home/diego/MagicMirror/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/home/diego/MagicMirror/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/diego/MagicMirror/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/diego/.npm/_logs/2020-05-06T16_07_25_651Z-debug.log

**Comment by bugsounet** [comment]
wow ...
You have not permission to write into your home ...

try this : 
```sh
ls -la /home
```

**Comment by jimenezfuentesd** [comment]
> > i had an issue with vendor and fonts folders
> 
> that's why you have issue ...

I don't think that's the problem because on a previous installation of MM all was working correctly except assistant module...

**Comment by bugsounet** [comment]
ok so, make it as you want :)
