### ISSUE TITLE
routine google home

### ISSUE THREAD

**Issue by marcgrc** [bugsounet/MMM-AssistantMk2#387]
**Describe the problem**
A clear and concise description of what the problem you have.

**To Reproduce**
Steps to reproduce the behavior: (Describe what did you do)

**Expected behavior**

**Screenshots**

**Environment:**
 - Device : [e.g. RPI 3b+]
 - OS: [e.g. Raspbian Stretch]
 - Node Version :
 - Etc.

**Before you post issue, try this first**
- Confirm you have completed installation with instruction. (If you have a problem on installation step, find other similar issues or follow instruction carefully. But if you failed again, post issue here.)
- To make things simple, disable or omit or outcomment other modules from config.js except MMM-AssistantMk2 and MMM-Hotword.
- Add `verbose:true` to MMM-Assistant `config:{}` and `testMic:true` to MMM-Hotword `config:{}`. 
- Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
- If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.

Then report me.

**Comment by marcgrc** [comment]
why even if the MY 1 st Mirror is registered on google home when i tell jarvis to run a routine it doesn't?

**Comment by bugsounet** [comment]
AMK2 is an google SDK project, so it not reconized like a Real google device

To be clear : SDK equal to a developer project and not all functionnality are activated
I just apply this API

**Comment by marcgrc** [comment]
which API?
can I solve the problem of enabling my routines?
please thank you

**Comment by bugsounet** [comment]
Application Programming Interface = API
Google SDK is a kit for developing so it's not release by google and not reconized by google

so , you can't solve this :(
or wait ... if google deploy it ... a day maybe

Note: if this project (or module) is reconized by google, i have to pay $$$ and i don't want it
I prefer this module free rather than paying for it ;)

**Comment by marcgrc** [comment]
thank you

**Comment by marcgrc** [comment]
so is it normal that routines don't work?

**Comment by bugsounet** [comment]
yes it's normal, i can't active it

**Comment by marcgrc** [comment]
thank you
