### ISSUE TITLE
Assistant says Sorry I don't understand.

### ISSUE THREAD

**Issue by kevin07696** [bugsounet/MMM-AssistantMk2#388]
**Describe the problem**
Assistant says Sorry I don't understand when I'm testing Reboot-Restart-Shutdown.js recipe. I also can't ask it conversational questions like "What time is it?"

**To Reproduce**
Finished Auto Installation, Google Setup without issue. Added and configured MMM-Snowboy and MMM-Assistant2Display. Added Reboot-Restart-Shutdown.js to recipes in config.js

**Expected behavior**
Raspberry Pi shuts down. 

**Config.js**

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	timeFormat: 12,
	units: "imperial",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
		{
			module: "MMM-AssistantMk2",
			position: "fullscreen_above",
			config: {
				debug: false,
				ui: "Fullscreen", // Classic2, Classic or Simple
				// if you want Google Nest ui style
				// set Fullscreen ui AND fullscreen_above position
				assistantConfig: {
					projectId: "", // Required to use gaction.
					modelId: "", // (OPTIONAL for gaction)
					instanceId: "", // (OPTIONAL for gaction)
					latitude: 51.508530,
					longitude: -0.076132,
				},
				responseConfig: {
					useHTML5: true, // sound render by HTML5
					useScreenOutput: true,
					useAudioOutput: true,
					useChime: true,
					timer: 5000,
					myMagicWord: false,
					//Your prefer sound play program.
					//By example, if you are running this on OSX, `afplay` could be available.
					//by default mpg321 play program is enabled
					//if audio output cutting try with mpg123 or cvlc program
					playProgram: "mpg321",
					chime: {
						beep: "beep.mp3",
						error: "error.mp3",
						continue: "continue.mp3",
						open: "Google_beep_open.mp3",
						close: "Google_beep_close.mp3",
					},
					// false - animated icons, 'standby' - static icons only for standby state, true - all static icons
					useStaticIcons: false
				},
				micConfig: { // put there configuration generated by auto-installer
					recorder: "arecord",
					device: "plughw:1",
					channels: 4,
				},
				customActionConfig: {
					autoMakeAction: false,
					autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
					actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
				},
				recipes: [ "with-MMM-TelegramBot.js", "Reboot-Restart-Shutdown.js" ],
				profiles: {
					"default": {
						profileFile: "default.json",
						lang: "en-US"
					}
				},
				useA2D: true,
				A2DStopCommand: "stop",
				useSnowboy: false,
				snowboy: {
					audioGain: 2.0,
					Frontend: true,
					Model: "jarvis",
					Sensitivity: null
				},
			},
		},
		{
			module: 'MMM-Snowboy',
			config: {
				debug: false,
				AudioGain: 2.0,
				Frontend: true,
				Model: "jarvis",
				Sensitivity: null,
				micConfig: {
					recorder: "arecord",
					device: "plughw:1"
				},
				onDetected: {
					notification: "ASSISTANT_ACTIVATE",
					parameters: {
						type: "MIC",
						profile: "default",
						chime: true
					}
				}
			}
		},
		{
			module: "MMM-Assistant2Display",
			position: "top_left",
			config: {
				debug: false,
			}
		},
	]

};

**Backend Log:**
> magicmirror@2.11.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js "dev"

[2020-05-07 01:21:18.709] [LOG]    Starting MagicMirror: v2.11.0
[2020-05-07 01:21:18.772] [LOG]    Loading config ...
[2020-05-07 01:21:18.796] [LOG]    Loading module helpers ...
[2020-05-07 01:21:18.805] [LOG]    No helper found for module: alert.
[2020-05-07 01:21:18.815] [LOG]    No helper found for module: clock.
[2020-05-07 01:21:24.861] [LOG]    Initializing new module helper ...
[2020-05-07 01:21:24.865] [LOG]    Module helper loaded: MMM-AssistantMk2
[2020-05-07 01:21:25.723] [LOG]    Initializing new module helper ...
[2020-05-07 01:21:25.726] [LOG]    Module helper loaded: MMM-Snowboy
[2020-05-07 01:21:27.463] [LOG]    Initializing new module helper ...
[2020-05-07 01:21:27.466] [LOG]    Module helper loaded: MMM-Assistant2Display
[2020-05-07 01:21:27.467] [LOG]    All module helpers loaded.
[2020-05-07 01:21:28.010] [LOG]    Starting server on port 8080 ... 
[2020-05-07 01:21:28.065] [LOG]    Server started ...
[2020-05-07 01:21:28.068] [LOG]    Connecting socket for: MMM-AssistantMk2
[2020-05-07 01:21:28.071] [LOG]    Connecting socket for: MMM-Snowboy
[2020-05-07 01:21:28.073] [LOG]    [SNOWBOY] Starting...
[2020-05-07 01:21:28.076] [LOG]    Connecting socket for: MMM-Assistant2Display
[2020-05-07 01:21:28.078] [LOG]    Sockets connected & modules started ...
[2020-05-07 01:21:28.764] [LOG]    Launching application.
[2020-05-07 01:21:38.402] [LOG]    [SNOWBOY] Model selected: jarvis
[2020-05-07 01:21:38.431] [LOG]    [SNOWBOY] snowboy v1.4.7 Initialized...
[2020-05-07 01:21:38.744] [LOG]    [AMK2] MMM-AssistantMk2 Version: 3.2.3
[2020-05-07 01:21:38.748] [LOG]    [AMK2] Response delay is set to 0.5 second
[2020-05-07 01:21:38.755] [LOG]    [AMK2] Use HTML5 for audio response
[2020-05-07 01:21:38.781] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-TelegramBot.js
[2020-05-07 01:21:38.791] [LOG]    [AMK2] RECIPE_LOADED: Reboot-Restart-Shutdown.js
[2020-05-07 01:21:38.798] [LOG]    [AMK2] NO_ACTION_TO_MANAGE
[2020-05-07 01:21:38.804] [LOG]    [AMK2] Assistant2Display Server Started
[2020-05-07 01:21:38.810] [LOG]    [AMK2] ASSISTANT_WEB Started
[2020-05-07 01:21:38.813] [LOG]    [AMK2] AssistantMk2 is initialized.
[2020-05-07 01:21:38.854] [LOG]    [A2D] MMM-Assistant2Display Version: 1.4.1
[2020-05-07 01:21:38.861] [LOG]    [A2D] Assistant2Display is initialized.
[2020-05-07 01:25:22.048] [LOG]    [AMK2] QUERY: {
  type: 'MIC',
  profile: { profileFile: 'default.json', lang: 'en-US' },
  key: null,
  lang: null,
  useScreenOutput: true,
  useAudioOutput: true,
  useHTML5: true,
  session: 1588829121430,
  status: 'standby',
  chime: true,
  secretMode: false,
  sayMode: false
}
[2020-05-07 01:25:22.723] [LOG]    [AMK2:BM] MP3 FILE CREATING: /home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/lastResponse.mp3
[2020-05-07 01:25:22.741] [LOG]    [AMK2:AS] MIC:RECORDING START.
[2020-05-07 01:25:22.834] [LOG]    [AMK2:16] START LISTENING 4 channels with sample rate 16000
[2020-05-07 01:25:24.619] [LOG]    [AMK2:BM] MP3 FILE CREATED
[2020-05-07 01:25:24.622] [LOG]    [AMK2:AS] CONVERSATION_ERROR: Error: 3 INVALID_ARGUMENT: Invalid 'audio_in': audio frame length is too long.
[2020-05-07 01:25:24.630] [LOG]    [AMK2:AS] MIC:RECORDING_END
[2020-05-07 01:25:24.641] [LOG]    [AMK2:16] STOP LISTENING
[2020-05-07 01:25:24.661] [LOG]    [AMK2] ASSISTANT_RESULT {
  session: 1588829121430,
  error: 'NO_RESPONSE',
  action: null,
  text: null,
  screen: null,
  audio: null,
  transcription: null,
  continue: false,
  volume: null,
  lastQuery: {
    type: 'MIC',
    profile: { profileFile: 'default.json', lang: 'en-US' },
    key: null,
    lang: null,
    useScreenOutput: true,
    useAudioOutput: true,
    useHTML5: true,
    session: 1588829121430,
    status: 'standby',
    chime: true,
    secretMode: false,
    sayMode: false
  }
}
[2020-05-07 01:25:36.553] [LOG]    [AMK2] QUERY: {
  type: 'MIC',
  profile: { profileFile: 'default.json', lang: 'en-US' },
  key: null,
  lang: null,
  useScreenOutput: true,
  useAudioOutput: true,
  useHTML5: true,
  session: 1588829135982,
  status: 'standby',
  chime: true,
  secretMode: false,
  sayMode: false
}
[2020-05-07 01:25:36.613] [LOG]    [AMK2:BM] MP3 FILE CREATING: /home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/lastResponse.mp3
[2020-05-07 01:25:36.651] [LOG]    [AMK2:AS] MIC:RECORDING START.
[2020-05-07 01:25:36.828] [LOG]    [AMK2:16] START LISTENING 4 channels with sample rate 16000
[2020-05-07 01:25:37.694] [LOG]    [AMK2:AS] CONVERSATION:RESPONSE 
[2020-05-07 01:25:39.437] [LOG]    [AMK2:AS] CONVERSATION:END_OF_UTTERANCE
[2020-05-07 01:25:39.442] [LOG]    [AMK2:AS] MIC:RECORDING_END
[2020-05-07 01:25:39.451] [LOG]    [AMK2:16] STOP LISTENING
[2020-05-07 01:25:39.469] [LOG]    [AMK2:AS] CONVERSATION:RESPONSE 
[2020-05-07 01:25:39.539] [LOG]    [AMK2:AS] CONVERSATION_ALL_RESPONSES_RECEIVED
[2020-05-07 01:25:39.550] [LOG]    [AMK2:AS] CONVERSATION_END:COMPLETED
[2020-05-07 01:25:39.554] [LOG]    [AMK2:AS] CONVERSATION_PP:RESPONSE_AUDIO_TOO_SHORT_OR_EMPTY -  0
[2020-05-07 01:25:39.557] [LOG]    [AMK2:BM] MP3 FILE CREATED
[2020-05-07 01:25:39.561] [LOG]    [AMK2] ASSISTANT_RESULT {
  session: 1588829135982,
  error: 'NO_RESPONSE',
  action: null,
  text: null,
  screen: null,
  audio: null,
  transcription: null,
  continue: false,
  volume: null,
  lastQuery: {
    type: 'MIC',
    profile: { profileFile: 'default.json', lang: 'en-US' },
    key: null,
    lang: null,
    useScreenOutput: true,
    useAudioOutput: true,
    useHTML5: true,
    session: 1588829135982,
    status: 'standby',
    chime: true,
    secretMode: false,
    sayMode: false
  }
}
[2020-05-07 01:27:27.657] [LOG]    Shutting down server...
[2020-05-07 01:27:27.661] [LOG]    Stopping module helper: MMM-AssistantMk2
[2020-05-07 01:27:27.663] [LOG]    Stopping module helper: MMM-Snowboy
[2020-05-07 01:27:27.665] [LOG]    Stopping module helper: MMM-Assistant2Display
**Front End Log:**

loader.js:155 Scripts loaded for: clock
loader.js:194 Load stylesheet: modules/default/clock/clock_styles.css
loader.js:157 Styles loaded for: clock
loader.js:159 Translations loaded for: clock
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:479 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: /modules/MMM-AssistantMk2/components/response.js
loader.js:179 Load script: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
translator.js:175 MMM-AssistantMk2 - Load translation fallback: translations/en.json
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:179 Load script: modules/MMM-Snowboy//MMM-Snowboy.js
module.js:479 Module registered: MMM-Snowboy
loader.js:150 Bootstrapping module: MMM-Snowboy
loader.js:155 Scripts loaded for: MMM-Snowboy
loader.js:157 Styles loaded for: MMM-Snowboy
loader.js:159 Translations loaded for: MMM-Snowboy
loader.js:179 Load script: modules/MMM-Assistant2Display//MMM-Assistant2Display.js
module.js:479 Module registered: MMM-Assistant2Display
loader.js:150 Bootstrapping module: MMM-Assistant2Display
MMM-Assistant2Display.js:380 [A2D] Scan config.js file
MMM-Assistant2Display.js:396 [A2D] MMM-Snowboy detected!
MMM-Assistant2Display.js:411 [A2D] Auto choice UI Fullscreen
loader.js:179 Load script: /modules/MMM-Assistant2Display/components/display.js
loader.js:179 Load script: /modules/MMM-Assistant2Display/ui/Fullscreen/Fullscreen.js
loader.js:179 Load script: /modules/MMM-Assistant2Display/components/youtube.js
loader.js:155 Scripts loaded for: MMM-Assistant2Display
loader.js:194 Load stylesheet: /modules/MMM-Assistant2Display/ui/Fullscreen/Fullscreen.css
loader.js:194 Load stylesheet: modules/MMM-Assistant2Display/screen.css
loader.js:157 Styles loaded for: MMM-Assistant2Display
translator.js:175 MMM-Assistant2Display - Load translation fallback: translations/en.json
loader.js:159 Translations loaded for: MMM-Assistant2Display
loader.js:194 Load stylesheet: css/custom.css
(index):1 Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:203 Error on loading stylesheet: css/custom.css
alert.js:153 Starting module: alert
clock.js:45 Starting module: clock
display.js:40 [A2D] DisplayClass Loaded
Fullscreen.js:4 [A2D] Extend Display with Fullscreen ui Loaded
MMM-Assistant2Display.js:149 [A2D] initialized.
main.js:474 All modules started!
youtube.js:60 [A2D] YOUTUBE Class Loaded
MMM-AssistantMk2.js:344 [AMK2] Initialized.
response.js:77 [AMK2] Status from standby to standby
MMM-AssistantMk2.js:608 [AMK2] Command TELBOT_READY is executed (moduleExec) for : MMM-AssistantMk2
7
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').
module.js:198 alert is suspended.
module.js:198 MMM-Snowboy is suspended.
module.js:198 clock is suspended.
response.js:77 [AMK2] Status from standby to listen
response.js:77 [AMK2] Status from listen to error
response.js:142 [AMK2] Conversation ends.
response.js:77 [AMK2] Status from error to standby
module.js:205 alert is resumed.
module.js:205 MMM-Snowboy is resumed.
module.js:205 clock is resumed.
module.js:198 alert is suspended.
module.js:198 MMM-Snowboy is suspended.
module.js:198 clock is suspended.
response.js:77 [AMK2] Status from standby to listen
response.js:77 [AMK2] Status from listen to error
response.js:142 [AMK2] Conversation ends.
response.js:77 [AMK2] Status from error to standby
module.js:205 alert is resumed.
module.js:205 MMM-Snowboy is resumed.
module.js:205 clock is resumed.
﻿
/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Environment:**
 - Device : [e.g. RPI 3b+]
 - OS: [e.g. Raspbian Stretch]
 - Node Version :
 - Etc.

**Before you post issue, try this first**
- Confirm you have completed installation with instruction. (If you have a problem on installation step, find other similar issues or follow instruction carefully. But if you failed again, post issue here.)
- To make things simple, disable or omit or outcomment other modules from config.js except MMM-AssistantMk2 and MMM-Hotword.
- Add `verbose:true` to MMM-Assistant `config:{}` and `testMic:true` to MMM-Hotword `config:{}`. 
- Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
- If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.

Then report me.

**Comment by bugsounet** [comment]
hi,

```
			micConfig: { // put there configuration generated by auto-installer
				recorder: "arecord",
				device: "plughw:1",
				channels: 4,
			},
```

why `channels:4` ?
conversation to google need only 1 channel
so, by removing `channels` ligne will resolve this issue

**Comment by kevin07696** [comment]
Thanks so much it works now. But can I ask I have 4 mics on my respeaker does this mean it will only use one of them?

**Comment by bugsounet** [comment]
yes, i have not no solution about this, actually

**Comment by kevin07696** [comment]
thanks anyways
