### ISSUE TITLE
Assistant not showing up in MM

### ISSUE THREAD

**Issue by NotWeelee** [bugsounet/MMM-AssistantMk2#389]
After following the steps in the wiki to set up everything needed for Assistant, the Assistant UI is not showing up in Magic Mirror.

![screenshot](https://user-images.githubusercontent.com/44516414/81336874-b58e6880-906f-11ea-93a5-dce2c09ae5de.png)

With all the modules other than MMM-AssistantMk2 and MMM-Hotword disabled, MM just shows a black screen.

 - Device : RPI 3b+
 - OS: Raspbian Buster
 - Node Version : 10.20.1
 - GCC Version: 7

Logs:

Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/en.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:479 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: /modules/MMM-AssistantMk2/components/response.js
loader.js:179 Load script: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
translator.js:175 MMM-AssistantMk2 - Load translation fallback: translations/en.json
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
  protocols.This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/MMM-AssistantMk2//MMM-AssistantMk2.js
- http://localhost:8080/modules/MMM-AssistantMk2/components/response.js
- http://localhost:8080/modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.js
- http://localhost:8080/modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.css

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
(anonymous) @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:179 Load script: modules/MMM-Hotword//MMM-Hotword.js
MMM-Hotword.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
loader.js:187 Error on loading script: modules/MMM-Hotword//MMM-Hotword.js
script.onerror @ loader.js:187
loader.js:194 Load stylesheet: css/custom.css
(index):1 Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:203 Error on loading stylesheet: css/custom.css
stylesheet.onerror @ loader.js:203
main.js:474 All modules started!

[2020-05-07 15:27:22.347] [LOG]    Starting MagicMirror: v2.11.0
[2020-05-07 15:27:22.359] [LOG]    Loading config ...
[2020-05-07 15:27:22.375] [LOG]    Loading module helpers ...
[2020-05-07 15:27:25.008] [LOG]    Initializing new module helper ...
[2020-05-07 15:27:25.010] [LOG]    Module helper loaded: MMM-AssistantMk2
[2020-05-07 15:27:25.011] [LOG]    No helper found for module: MMM-Hotword.
[2020-05-07 15:27:25.012] [LOG]    All module helpers loaded.
[2020-05-07 15:27:25.289] [LOG]    Starting server on port 8080 ... 
[2020-05-07 15:27:25.316] [LOG]    Server started ...
[2020-05-07 15:27:25.318] [LOG]    Connecting socket for: MMM-AssistantMk2
[2020-05-07 15:27:25.319] [LOG]    Sockets connected & modules started ...
[2020-05-07 15:27:25.535] [LOG]    Launching application.
[2020-05-07 15:27:29.126] [LOG]    [AMK2] MMM-AssistantMk2 Version: 3.2.3
[2020-05-07 15:27:29.128] [LOG]    [AMK2] Use HTML5 for audio response
[2020-05-07 15:27:29.145] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-Spotify.js
[2020-05-07 15:27:29.161] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-Hotword.js
[2020-05-07 15:27:29.164] [LOG]    [AMK2] ASSISTANT_WEB Started
[2020-05-07 15:27:29.166] [LOG]    [AMK2] AssistantMk2 is initialized.

Config.js :

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	timeFormat: 12,
	units: "imperial",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "MMM-AssistantMk2",
			position: "top_right",
			ui: "Classic",
			config: {
				assistantConfig: {
					latitude: 41.652682,
					longitude: -91.532854,
				},
				recipes: ["with-MMM-Spotify.js", "with-MMM-Hotword.js"],
				profiles: {
					"default": {
						profileFile: "default.json",
						lang: "en-US"
					}
				},
				micconfig: {
					recorder: "arecord",
					device: "plughw:1",
				},
				verbose:true
			}
		},
		{
			module: "MMM-Hotword",
			position: "bottom_left",
			config: {
				useDisplay: false,
				chimeOnFinish: null,
				recipes: ["with-AMk2v3_smart-mirror.js"],
				mic: {
					recordProgram: "arecord",
					device: "plughw:1"
				},
				testMic: true
			}
		}
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

Please let me know if you need anything else

**Comment by bugsounet** [comment]
> loader.js:179 Load script: modules/MMM-Hotword//MMM-Hotword.js
MMM-Hotword.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
loader.js:187 Error on loading script: modules/MMM-Hotword//MMM-Hotword.js

i think it's not related to AMk2

**Comment by NotWeelee** [comment]
I just tried removing MMM-Hotword and I still get a black screen.

Logs without MMM-Hotword:

Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/en.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:479 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: /modules/MMM-AssistantMk2/components/response.js
loader.js:179 Load script: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: /modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
translator.js:175 MMM-AssistantMk2 - Load translation fallback: translations/en.json
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
  protocols.This exposes users of this app to unnecessary security risks.
  Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/en.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/MMM-AssistantMk2//MMM-AssistantMk2.js
- http://localhost:8080/modules/MMM-AssistantMk2/components/response.js
- http://localhost:8080/modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.js
- http://localhost:8080/modules/MMM-AssistantMk2/ui/Fullscreen/Fullscreen.css
  
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:95
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
(anonymous) @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:145
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: css/custom.css
(index):1 Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
loader.js:203 Error on loading stylesheet: css/custom.css
stylesheet.onerror @ loader.js:203
main.js:474 All modules started!
(index):1 Refused to apply style from 'http://localhost:8080/css/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

[2020-05-08 11:44:37.056] [LOG]    Starting MagicMirror: v2.11.0
[2020-05-08 11:44:37.081] [LOG]    Loading config ...
[2020-05-08 11:44:37.099] [LOG]    Loading module helpers ...
[2020-05-08 11:44:41.162] [LOG]    Initializing new module helper ...
[2020-05-08 11:44:41.165] [LOG]    Module helper loaded: MMM-AssistantMk2
[2020-05-08 11:44:41.167] [LOG]    All module helpers loaded.
[2020-05-08 11:44:41.585] [LOG]    Starting server on port 8080 ... 
[2020-05-08 11:44:41.637] [LOG]    Server started ...
[2020-05-08 11:44:41.642] [LOG]    Connecting socket for: MMM-AssistantMk2
[2020-05-08 11:44:41.645] [LOG]    Sockets connected & modules started ...
[2020-05-08 11:44:41.958] [LOG]    Launching application.
[2020-05-08 11:44:45.544] [LOG]    [AMK2] MMM-AssistantMk2 Version: 3.2.3
[2020-05-08 11:44:45.546] [LOG]    [AMK2] Use HTML5 for audio response
[2020-05-08 11:44:45.557] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-Spotify.js
[2020-05-08 11:44:45.561] [LOG]    [AMK2] ASSISTANT_WEB Started
[2020-05-08 11:44:45.562] [LOG]    [AMK2] AssistantMk2 is initialized.

**Comment by bugsounet** [comment]
try updating AMk2 with this command in AMk2 directory:

```npm run update```
