### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by marcgrc** [bugsounet/MMM-AssistantMk2#391]
But sorry only my MM is late and the bro to answer or rather the hot word hears it immediately also because I raised the gain of the mic, but the rest is almost bad almost unusable if you do not have great patience. You have to wait before saying a command after Jarvis, for example, then the answers are late. To explain it better far away from Google mini but is this normal? Solutions

**Comment by bugsounet** [comment]
hi, what detector are you using ?

**Comment by marcgrc** [comment]
Hotword

**Comment by bugsounet** [comment]
what is your recipe used ?

**Comment by marcgrc** [comment]
![8BD9E327-533D-4978-AE87-95F192A415D8](https://user-images.githubusercontent.com/19284774/81467870-de337100-91db-11ea-804d-51efbed2e33c.jpeg)
![566714E5-07C6-4A37-A249-FF9ED1A16143](https://user-images.githubusercontent.com/19284774/81467874-e25f8e80-91db-11ea-9057-2ca36295fe48.jpeg)

**Comment by marcgrc** [comment]
![048159BD-8785-4D21-8C4B-38084C25DA24](https://user-images.githubusercontent.com/19284774/81467946-703b7980-91dc-11ea-9812-082360830e34.jpeg)

**Comment by bugsounet** [comment]
change your Hotword recipe to : 
```js
recipes: [ "with-AMk2v3-noisy_Jarvis.js"]
```js
and delete `detectorAudioGain` line

now when you call assistant you will ear the AMk2 beep and we can ask your question
tel me if it's better

**Comment by marcgrc** [comment]
beautiful is better.
another flaw is this ..
when I tell Jarvis I have to pause before saying a command because if he doesn't hear it. it would be nice to say Jarvis and command below.
if it resolves, it's like a google mini 💪💪

**Comment by bugsounet** [comment]
with your first recipe used, it's normaly that ... but if there is so noisy environement it not works correctly...
for you, i think it's the noisy recipe, it's the better solution.
I can't do better actually

**Comment by marcgrc** [comment]
I'm in a closed garage however it works well only that between the word jarvis and the command you have to wait a second, it can't listen
below.
I hope I have explained myself well😁

**Comment by bugsounet** [comment]
`recipes: ["with-AMk2v3_Jarvis.js"]`
for working you have to say : `Jarvis, what time is it ?` -> AMk2 beep -> got the response
but you have not confirmation if `jarvis` is  recognized

recipes: [ "with-AMk2v3-noisy_Jarvis.js"]
for working you have to say: `jarvis` -> AMk2 beep -> `what time is it ?` -> got the reponse

I have not other method for activating assistant.
Reponse depend of you connexion speed and ... raspberry pi power ...

**Comment by bugsounet** [comment]
we think the main problem of this issue is solved
