### ISSUE TITLE
detection après "alexa"

### ISSUE THREAD

**Issue by jeff44850** [bugsounet/MMM-AssistantMk2#398]
bonjour 
est-ce qu'il y aurais une commande pour désactiver à la détection du mot Hotword et le réactiver ensuite ?
le soucis est que lorsque spotify ou youtube fonctionne hotword écoute les commandes vocales mais aussi les paroles des chansons.

**Comment by bugsounet** [comment]
Bonjour,
Voir [ici](https://github.com/bugsounet/MMM-Assistant2Display/issues/36). Donc non, il n'ira plus de mise à jour

bonne journée

**Comment by jeff44850** [comment]
Je ne comprends pas désolé mais ça me renvoie sur une autre discussion 🤔

**Comment by bugsounet** [comment]
c'est peut-etre la source du probleme...
