### ISSUE TITLE
Choosing options in new ui of actions console

### ISSUE THREAD

**Issue by yoonsoln** [bugsounet/MMM-AssistantMk2#403]
**Describe the problem**
I was making a new project in Actions Console(https://console.actions.google.com) and I don't know what to choose in new ui of this actions console.
(https://github.com/bugsounet/MMM-AssistantMk2/wiki/Google-Assistant-Setup)

**To Reproduce**
Go to https://console.actions.google.com and make a new project.

**Expected behavior**
You can meet a new ui of Actions Console.

**Screenshots**
![image](https://user-images.githubusercontent.com/43337517/82676545-8c7df280-9c81-11ea-87f1-2161673d43b3.png)

**Environment:**
 - Device :  RPI 3b+
 - OS: Raspbian Buster
 - Node Version : latest(20200520)
 - Etc.

By the way, thank you for making a Good Project.

**Comment by wlmqpsc** [comment]
Hi! May be you can choose the "Smart Home". It worked good when I test.
;)

**Comment by yoonsoln** [comment]
Thanks!!
