### ISSUE TITLE
during installation

### ISSUE THREAD

**Issue by AndrewGSefin** [bugsounet/MMM-AssistantMk2#409]
during the installation i have this message 
utils.sh: line 175:  1427 Floating point exceptionplay beep_check.wav 2> /dev/null

![image](https://user-images.githubusercontent.com/50564235/82758887-86a32100-9de9-11ea-9c55-03a122f47406.png)

**Comment by wlmqpsc** [comment]
enmm? check whether you have download all the MK2 and the file location is correct!
From this screenshot, it just can not find the recording with the beep.
But you can still install and config your MK2. Looks like it will not affect the function.

**Comment by bugsounet** [comment]
AMk2 v3 is now deprecied,
retry installation of AMk2 v2 with fresh source and old wiki
