### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by onehardybattler** [bugsounet/MMM-AssistantMk2#412]
**Describe the problem**
A clear and concise description of what the problem you have.

**To Reproduce**
Steps to reproduce the behavior: (Describe what did you do)

**Expected behavior**

**Screenshots**

**Environment:**
 - Device : [e.g. RPI 3b+]
 - OS: [e.g. Raspbian Stretch]
 - Node Version :
 - Etc.

**Before you post issue, try this first**
- Confirm you have completed installation with instruction. (If you have a problem on installation step, find other similar issues or follow instruction carefully. But if you failed again, post issue here.)
- To make things simple, disable or omit or outcomment other modules from config.js except MMM-AssistantMk2 and MMM-Hotword.
- Add `verbose:true` to MMM-Assistant `config:{}` and `testMic:true` to MMM-Hotword `config:{}`. 
- Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
- If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.

Then report me.

**Comment by onehardybattler** [comment]
I saw your disclaimer and it seems to me that you are frustrated. Please know that your contributions are valued by people like me who would have no way of building this on our own. I went through two other outdated modules before I tried yours. The fact that you work so hard to keep this updated is amazing to me. Keep up the good work. You are amazing.

**Comment by bugsounet** [comment]
hello, I will not say more on the subject.
thank you anytime.
You can still install the old version of AMk2 (v2)
it should be functional (I didn't test it)
