### ISSUE TITLE
This app is not yet configured to make OAuth requests

### ISSUE THREAD

**Issue by PineMaster** [bugsounet/MMM-AssistantMk2#417]
i keep getting error 
`This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console.`
at the 
cd ~/MagicMirror/modules/MMM-AssistantMk2
node auth_and_test.js 
part

**Comment by timbuktu031** [comment]
> i keep getting error
> `This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console.`
> at the
> cd ~/MagicMirror/modules/MMM-AssistantMk2
> node auth_and_test.js
> part

You need to create a consent screen in the cloud console. There is no such mention in the installation guide, so it seems to be missing.

**Comment by PineMaster** [comment]
fixed
