### ISSUE TITLE
Ignoring Yoube after update

### ISSUE THREAD

**Issue by meusprojetoskali** [bugsounet/MMM-AssistantMk2#429]
After updating to version 3.6, assistant responds to any request, but ignores any request that contains the phrase YOUTUBE, responding only with "I don't understand".

**Comment by bugsounet** [comment]
sorry, but I don't see the problem.

In all case:
 * only audio response
 * no visual reponse
 * can't launch any prpgram
 * can't be linked to another module

please read wiki pages
